// generated by build_merit.py -- do not edit by hand
window.CAMPUS_MERIT={
 "UC Berkeley": {
  "pct": 2,
  "avg": 13175,
  "programs": "Regents' and Chancellor's Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Davis": {
  "pct": 3,
  "avg": 8659,
  "programs": "Regents Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Irvine": {
  "pct": 3,
  "avg": 12649,
  "programs": "Regents' Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UCLA": {
  "pct": 4,
  "avg": 8557,
  "programs": "Regents Scholarship; Alumni Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Merced": {
  "pct": 6,
  "avg": 7832,
  "programs": "Regents Scholarship; Chancellor's Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Riverside": {
  "pct": 2,
  "avg": 5791,
  "programs": "Regents Scholarship; Chancellor's Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC San Diego": {
  "pct": 3,
  "avg": 14948,
  "programs": "Regents Scholarship ($5,000/yr)",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Santa Barbara": {
  "pct": 2,
  "avg": 12372,
  "programs": "Regents Scholarship (top 2% of admits)",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Santa Cruz": {
  "pct": 8,
  "avg": 8313,
  "programs": "Regents Scholarship; Campus Merit Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "CSU Bakersfield": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "CSU Channel Islands": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Chico State": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "CSU Dominguez Hills": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State East Bay": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Fresno State": {
  "pct": 6,
  "avg": 3304,
  "programs": "President's, Smittcamp Family Honors College (full)",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State Fullerton": {
  "pct": 19,
  "avg": 2590,
  "programs": "University Honors and departmental awards",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal Poly Humboldt": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State Long Beach": {
  "pct": 4,
  "avg": 1280,
  "programs": "President's Scholars (full ride, valedictorians and National Merit)",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State LA": {
  "pct": 4,
  "avg": 6655,
  "programs": "Presidential Scholars; Honors College",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State Monterey Bay": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State Northridge": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal Poly Pomona": {
  "pct": 2,
  "avg": 1255,
  "programs": "Kellogg Honors College awards",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Sacramento State": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State San Bernardino": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "San Diego State": {
  "pct": 1,
  "avg": 3811,
  "programs": "Presidential and Dean's scholarships",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "San Francisco State": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "San José State": {
  "pct": 2,
  "avg": 3146,
  "programs": "Campus scholarships",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal Poly San Luis Obispo": {
  "pct": 7,
  "avg": 3746,
  "programs": "Cal Poly Scholars and departmental awards",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State San Marcos": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Sonoma State": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Stanislaus State": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal Poly Maritime Academy": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Brown": {
  "pct": 0.3,
  "avg": 21278,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Columbia": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Cornell": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Dartmouth": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Harvard": {
  "pct": 0.1,
  "avg": 6000,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Penn": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Princeton": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Yale": {
  "pct": 0.4,
  "avg": 27333,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Williams": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Amherst": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Swarthmore": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Pomona": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Wellesley": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Bowdoin": {
  "pct": 2,
  "avg": 1000,
  "programs": "National Merit supplement only",
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Carleton": {
  "pct": 2,
  "avg": 15761,
  "programs": "National Merit and a few named awards",
  "note": "Almost entirely need-based; a small number of National Merit and named scholarships."
 },
 "Middlebury": {
  "pct": 0.2,
  "avg": 5000,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Davidson": {
  "pct": 3,
  "avg": 41262,
  "programs": "Belk, Baker, and Bryan Scholars (full tuition and more)",
  "note": "A few very large competitive scholarships (about 3% of no-need freshmen) rather than broad merit aid; separate application and finalist weekend."
 },
 "Harvey Mudd": {
  "pct": 17,
  "avg": 10457,
  "programs": "Harvey S. Mudd Merit Award ($10,000/yr); President's Scholars (full tuition, about 20 students)",
  "note": "Merit awards are automatic with admission for roughly one in six no-need students; the full-tuition President's Scholars program is competitive."
 },
 "Claremont McKenna": {
  "pct": 8,
  "avg": 23300,
  "programs": "McKenna Achievement Award ($20,000/yr); Interdisciplinary Science Scholarship",
  "note": "Awarded with admission to a small share of the strongest applicants; no separate application."
 },
 "Haverford": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Vassar": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Grinnell": {
  "pct": 23,
  "avg": 26154,
  "programs": "Trustee, Founders, and Presidential Scholarships (up to about $30,000/yr)",
  "note": "Merit is a deliberate strategy here: nearly a quarter of no-need freshmen get an award averaging over $26,000, considered automatically with the application."
 },
 "Wesleyan": {
  "pct": 0.1,
  "avg": 20553,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Scripps": {
  "pct": 15,
  "avg": 24048,
  "programs": "James E. Scripps Scholarship (half tuition); New Generation Scholarship",
  "note": "Half-tuition James E. Scripps awards go to top admits; considered automatically."
 },
 "Pitzer": {
  "pct": 2,
  "avg": 7000,
  "programs": "Trustee Community Scholarship",
  "note": "Very little merit money; aid is essentially need-based."
 },
 "Occidental": {
  "pct": 29,
  "avg": 17397,
  "programs": "Presidential, Trustee, Faculty, and Dean's Scholarships (up to about $30,000/yr)",
  "note": "Nearly a third of no-need freshmen receive merit, awarded with admission based on grades and rigor; no separate application."
 },
 "Whitman": {
  "pct": 37,
  "avg": 21981,
  "programs": "Merit scholarships awarded with admission (up to about $25,000/yr)",
  "note": "The most merit-generous school in this tour: over a third of no-need freshmen get an award averaging about $22,000, decided from the application itself."
 },
 "Reed": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Reed awards aid on need only, apart from National Merit."
 },
 "Stanford": {
  "pct": 0.1,
  "avg": 4150,
  "programs": null,
  "note": "Need-based only; no academic merit scholarships (athletic aid aside)."
 },
 "Caltech": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based only."
 },
 "USC": {
  "pct": 27,
  "avg": 20312,
  "programs": "Trustee (full tuition), Presidential (half), Deans (quarter), and Mork scholarships",
  "note": "Merit is real at USC: over a quarter of no-need freshmen get an award, but the big ones require applying by the December 1 scholarship deadline and an interview."
 },
 "Santa Clara": {
  "pct": 13,
  "avg": 16788,
  "programs": "Provost, Dean's, and Johnson Scholars",
  "note": "Merit goes to the strongest admits automatically; the Johnson Scholars program is full tuition and competitive."
 },
 "Loyola Marymount": {
  "pct": 53,
  "avg": 10762,
  "programs": "Trustee, Presidential, and Arrupe scholarships",
  "note": "More than half of no-need freshmen receive merit, automatically with admission."
 },
 "University of San Diego": {
  "pct": 20,
  "avg": 23136,
  "programs": "Presidential, Trustee, and Alcala scholarships",
  "note": "A fifth of no-need freshmen receive merit averaging over $23,000; considered automatically."
 },
 "Pepperdine": {
  "pct": 32,
  "avg": 7158,
  "programs": "Academic and Regents' scholarships",
  "note": "About a third receive merit, though awards are modest against the sticker price."
 },
 "Chapman": {
  "pct": 18,
  "avg": 23936,
  "programs": "Presidential, Chancellor's, and Dean's scholarships",
  "note": "Merit awards near $24,000 go to roughly one in five no-need freshmen, automatically with admission."
 },
 "University of Portland": {
  "pct": 23,
  "avg": 29685,
  "programs": "Presidential and Holy Cross scholarships",
  "note": "Large automatic merit awards (average near $30,000) make the net price far below sticker for strong students."
 },
 "Gonzaga": {
  "pct": 42,
  "avg": 22532,
  "programs": "Dean's, Trustee, and Regents scholarships",
  "note": "Merit is the norm: over 40% of no-need freshmen get an award averaging $22,500, automatically with admission."
 },
 "MIT": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based only; MIT gives no merit scholarships."
 },
 "University of Chicago": {
  "pct": 4,
  "avg": 16338,
  "programs": "Dean's and University Scholarships",
  "note": "A few merit awards; aid is overwhelmingly need-based (and no-loan)."
 },
 "Duke": {
  "pct": 1,
  "avg": 85600,
  "programs": "Robertson, A.B. Duke, and Reginaldo Howard Scholars",
  "note": "A handful of full-ride programs with separate nominations; not a merit school in the ordinary sense."
 },
 "Northwestern": {
  "pct": 1,
  "avg": 20625,
  "programs": null,
  "note": "Essentially need-based only."
 },
 "Johns Hopkins": {
  "pct": 4,
  "avg": 22347,
  "programs": "Hodson Trust Scholarship",
  "note": "A small number of merit awards; aid is need-based and loan-free."
 },
 "Rice": {
  "pct": 4,
  "avg": 22318,
  "programs": "Trustee Distinguished Scholarships",
  "note": "A few merit awards; Rice's strength is generous need-based aid (tuition-free under $75,000 income)."
 },
 "Vanderbilt": {
  "pct": 9,
  "avg": 29973,
  "programs": "Cornelius Vanderbilt, Ingram, and Chancellor's Scholarships (full tuition)",
  "note": "Full-tuition merit for about 9% of no-need freshmen; requires the December 1 scholarship application."
 },
 "Notre Dame": {
  "pct": 2,
  "avg": 22952,
  "programs": "Stamps and Notre Dame Scholars",
  "note": "Very limited merit; aid is need-based."
 },
 "Carnegie Mellon": {
  "pct": 2,
  "avg": 12949,
  "programs": null,
  "note": "Almost entirely need-based."
 },
 "Georgetown": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based only."
 },
 "Tufts": {
  "pct": 4,
  "avg": 45237,
  "programs": null,
  "note": "A few large awards; aid is need-based."
 },
 "Boston College": {
  "pct": 2,
  "avg": 24920,
  "programs": "Gabelli Presidential Scholars (full tuition)",
  "note": "A small full-tuition program by separate nomination; otherwise need-based."
 },
 "Northeastern": {
  "pct": 13,
  "avg": 16112,
  "programs": "Dean's and merit scholarships",
  "note": "Merit awards around $16,000 go to about one in eight no-need freshmen, automatically."
 },
 "Boston University": {
  "pct": 8,
  "avg": 47920,
  "programs": "Presidential (half tuition) and Trustee (full tuition) Scholarships",
  "note": "Large but selective merit awards (December 1 deadline); most aid is need-based."
 },
 "NYU": {
  "pct": 1,
  "avg": 23737,
  "programs": null,
  "note": "Essentially need-based only; NYU's aid is also thinner than peers'."
 },
 "Wake Forest": {
  "pct": 2,
  "avg": 22262,
  "programs": "Nancy Susan Reynolds and Stamps Scholarships",
  "note": "A few competitive full-ride awards; otherwise need-based."
 },
 "Case Western Reserve": {
  "pct": 37,
  "avg": 30499,
  "programs": "University, Provost, and Michelson-Morley scholarships (up to full tuition)",
  "note": "One of the most merit-generous research universities: over a third of no-need freshmen get awards averaging $30,000, automatically with admission."
 },
 "Tulane": {
  "pct": 23,
  "avg": 21264,
  "programs": "Presidential, Founders, and Dean's Honor scholarships",
  "note": "Merit awards near $21,000 go to about a quarter of no-need freshmen; the largest require a December 15 application."
 },
 "Emory": {
  "pct": 5,
  "avg": 38751,
  "programs": "Emory Scholars (Woodruff, full tuition)",
  "note": "Competitive Emory Scholars program by school nomination; otherwise need-based."
 },
 "McGill": {
  "pct": null,
  "avg": null,
  "programs": "Entrance Scholarship (CAD 3,000, automatic); Major Entrance Scholarships (CAD 3,000-10,000 a year, renewable, separate application)",
  "note": "McGill reviews entrance scholarships on grades and test scores.",
  "intl": true,
  "lvl": 3
 },
 "UBC": {
  "pct": null,
  "avg": null,
  "programs": "International Major Entrance Scholarship (CAD 10,000-25,000 a year, renewable; automatic consideration); Outstanding International Student Award (CAD 10,000-25,000, one time)",
  "note": "Competitive awards; apply by the deadline to be considered.",
  "intl": true,
  "lvl": 2
 },
 "University of Toronto": {
  "pct": null,
  "avg": null,
  "programs": "Lester B. Pearson International Scholarship (full tuition, books, fees, and residence for 4 years; about 37 a year); U of T Scholars (CAD 10,000, one time, about 900 awards, automatic)",
  "note": "Pearson requires a nomination from your high school.",
  "intl": true,
  "lvl": 2
 },
 "Concordia": {
  "pct": null,
  "avg": null,
  "programs": "Limited for international students: Garnet Key Entrance Award (CAD 850); program-specific awards (CAD 2,500-7,500, deadline early December); John Molson CIBC Entrance Scholarship (CAD 5,000, essay)",
  "note": "Concordia's CAD 4,000 Undergraduate Excellence Award is limited to students in Canada.",
  "intl": true,
  "lvl": 2
 },
 "McMaster": {
  "pct": null,
  "avg": null,
  "programs": "International entrance awards: Science Global Scholars (CAD 10,000, then 7,500 a year); Social Sciences/Humanities Scholars (CAD 10,000, then 5,000 a year, 85%+ average); engineering and computer science awards (CAD 10,000); Award of Excellence (up to CAD 200,000 over 4 years)",
  "note": "Several awards are tied to your admission average.",
  "intl": true,
  "lvl": 3
 },
 "Memorial": {
  "pct": null,
  "avg": null,
  "programs": "International Entrance Scholarship (up to CAD 6,000, automatic); Killam American Undergraduate Scholarship (for U.S. citizens)",
  "note": "Entrance scholarships are first-year awards assessed automatically.",
  "intl": true,
  "lvl": 3
 },
 "St Andrews": {
  "pct": null,
  "avg": null,
  "programs": "International Excellence Scholarship (full tuition every year, merit); International Undergraduate Scholarship (need-based tuition reduction)",
  "note": "Scholarship applications are due in late January.",
  "intl": true,
  "lvl": 2
 },
 "Edinburgh": {
  "pct": null,
  "avg": null,
  "programs": "No general merit scholarship for international first-years; a few subject awards (e.g., Global Undergraduate Mathematics Scholarship, GBP 5,000)",
  "note": "Plan on paying the full fee.",
  "intl": true,
  "lvl": 1
 },
 "Glasgow": {
  "pct": null,
  "avg": null,
  "programs": "World Changers Global Excellence Scholarship (GBP 7,000 a year in arts and social sciences, GBP 10,000 in sciences; renewable)",
  "note": "A tuition discount renewed with satisfactory progress.",
  "intl": true,
  "lvl": 3
 },
 "Trinity College Dublin": {
  "pct": null,
  "avg": null,
  "programs": "Global Excellence Undergraduate Scholarship (EUR 2,000-5,000 off first-year tuition, rolling; some programs excluded)",
  "note": "Awarded on a rolling basis, so apply early.",
  "intl": true,
  "lvl": 3
 },
 "University College Dublin": {
  "pct": null,
  "avg": null,
  "programs": "Global Excellence Scholarship (50% or 100% of tuition, limited; apply by February 1 after an offer)",
  "note": "Apply by the December 1 priority deadline to be eligible.",
  "intl": true,
  "lvl": 2
 },
 "University of Amsterdam": {
  "pct": null,
  "avg": null,
  "programs": "Amsterdam University College Scholarship Fund (EUR 4,000, or up to 26,000 a year for non-EEA students, need-based); PPLE awards (EUR 5,000-10,000, a few a year)",
  "note": "The main university is not on the 2026-27 Holland Scholarship list.",
  "intl": true,
  "lvl": 1
 },
 "Maastricht": {
  "pct": null,
  "avg": null,
  "programs": "Holland Scholarship (EUR 5,000 in the first year); a need-based University College Maastricht scholarship for low-income non-EU students",
  "note": "Holland Scholarships are competitive.",
  "intl": true,
  "lvl": 2
 }
};
window.CAMPUS_MERIT_META={
 "source": "2024-25 Common Data Set section H2A via College Transitions merit-aid table (updated November 2025)",
 "url": "https://www.collegetransitions.com/dataverse/merit-aid",
 "definition": "pct = share of first-year students with no demonstrated financial need who received a non-need-based scholarship; avg = their average award per year"
};
