// generated by build_profile.py -- do not edit by hand
window.CAMPUS_PROFILE={
 "UC Berkeley": {
  "ratio": 18,
  "retention": 97,
  "townName": "Berkeley",
  "townPop": 124321,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 15
 },
 "UC Davis": {
  "ratio": 21,
  "retention": 93,
  "townName": "Davis",
  "townPop": 66850,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 75
 },
 "UC Irvine": {
  "ratio": 18,
  "retention": 94,
  "townName": "Irvine",
  "townPop": 307670,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 6
 },
 "UCLA": {
  "ratio": 18,
  "retention": 97,
  "townName": "Los Angeles",
  "townPop": 3898747,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 6
 },
 "UC Merced": {
  "ratio": 21,
  "retention": 83,
  "townName": "Merced",
  "townPop": 86333,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 110
 },
 "UC Riverside": {
  "ratio": 23,
  "retention": 88,
  "townName": "Riverside",
  "townPop": 314998,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 40
 },
 "UC San Diego": {
  "ratio": 19,
  "retention": 94,
  "townName": "San Diego",
  "townPop": 1386932,
  "townPopYear": "2020",
  "townNote": "La Jolla is a neighborhood of San Diego",
  "nature": 4,
  "beachMiles": 1
 },
 "UC Santa Barbara": {
  "ratio": 17,
  "retention": 92,
  "townName": "Santa Barbara",
  "townPop": 88665,
  "townPopYear": "2020",
  "townNote": "campus is in Isla Vista/Goleta next to Santa Barbara",
  "nature": 4,
  "beachMiles": 0
 },
 "UC Santa Cruz": {
  "ratio": 22,
  "retention": 90,
  "townName": "Santa Cruz",
  "townPop": 62956,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 5,
  "beachMiles": 2
 },
 "CSU Bakersfield": {
  "ratio": 16,
  "retention": 80,
  "townName": "Bakersfield",
  "townPop": 403455,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 110
 },
 "CSU Channel Islands": {
  "ratio": 15,
  "retention": 73,
  "townName": "Camarillo",
  "townPop": 70741,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 8
 },
 "Chico State": {
  "ratio": 20,
  "retention": 84,
  "townName": "Chico",
  "townPop": 101475,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 160
 },
 "CSU Dominguez Hills": {
  "ratio": 18,
  "retention": 66,
  "townName": "Carson",
  "townPop": 95558,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 9
 },
 "Cal State East Bay": {
  "ratio": 17,
  "retention": 79,
  "townName": "Hayward",
  "townPop": 162954,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 25
 },
 "Fresno State": {
  "ratio": 18,
  "retention": 78,
  "townName": "Fresno",
  "townPop": 542107,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 130
 },
 "Cal State Fullerton": {
  "ratio": 22,
  "retention": 85,
  "townName": "Fullerton",
  "townPop": 143617,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 14
 },
 "Cal Poly Humboldt": {
  "ratio": 14,
  "retention": 76,
  "townName": "Arcata",
  "townPop": 18857,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 5,
  "beachMiles": 6
 },
 "Cal State Long Beach": {
  "ratio": 19,
  "retention": 85,
  "townName": "Long Beach",
  "townPop": 466742,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 3
 },
 "Cal State LA": {
  "ratio": 19,
  "retention": 73,
  "townName": "Los Angeles",
  "townPop": 3898747,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 1,
  "beachMiles": 20
 },
 "Cal State Monterey Bay": {
  "ratio": 16,
  "retention": 79,
  "townName": "Seaside",
  "townPop": 32366,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 1
 },
 "Cal State Northridge": {
  "ratio": 21,
  "retention": 74,
  "townName": "Los Angeles",
  "townPop": 3898747,
  "townPopYear": "2020",
  "townNote": "Northridge is a San Fernando Valley neighborhood of Los Angeles",
  "nature": 2,
  "beachMiles": 20
 },
 "Cal Poly Pomona": {
  "ratio": 23,
  "retention": 88,
  "townName": "Pomona",
  "townPop": 151713,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 35
 },
 "Sacramento State": {
  "ratio": 21,
  "retention": 81,
  "townName": "Sacramento",
  "townPop": 524943,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 90
 },
 "Cal State San Bernardino": {
  "ratio": 19,
  "retention": 78,
  "townName": "San Bernardino",
  "townPop": 222101,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 55
 },
 "San Diego State": {
  "ratio": 22,
  "retention": 90,
  "townName": "San Diego",
  "townPop": 1386932,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 9
 },
 "San Francisco State": {
  "ratio": 16,
  "retention": 84,
  "townName": "San Francisco",
  "townPop": 873965,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 2
 },
 "San José State": {
  "ratio": 18,
  "retention": 86,
  "townName": "San Jose",
  "townPop": 1013240,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 1,
  "beachMiles": 30
 },
 "Cal Poly San Luis Obispo": {
  "ratio": 18,
  "retention": 95,
  "townName": "San Luis Obispo",
  "townPop": 47063,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 5,
  "beachMiles": 10
 },
 "Cal State San Marcos": {
  "ratio": 21,
  "retention": 75,
  "townName": "San Marcos",
  "townPop": 94833,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 15
 },
 "Sonoma State": {
  "ratio": 15,
  "retention": 75,
  "townName": "Rohnert Park",
  "townPop": 44390,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 25
 },
 "Stanislaus State": {
  "ratio": 16,
  "retention": 80,
  "townName": "Turlock",
  "townPop": 72740,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 100
 },
 "Cal Poly Maritime Academy": {
  "ratio": 10,
  "retention": 76,
  "townName": "Vallejo",
  "townPop": 126090,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 30
 },
 "Brown": {
  "ratio": 6,
  "retention": 99,
  "townName": "Providence",
  "townPop": 190934,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 25
 },
 "Columbia": {
  "ratio": 6,
  "retention": 97,
  "townName": "New York City",
  "townPop": 8804190,
  "townPopYear": "2020",
  "townNote": "Morningside Heights, Upper Manhattan",
  "nature": 1,
  "beachMiles": 15
 },
 "Cornell": {
  "ratio": 9,
  "retention": 98,
  "townName": "Ithaca",
  "townPop": 32108,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 5,
  "beachMiles": 250
 },
 "Dartmouth": {
  "ratio": 7,
  "retention": 98,
  "townName": "Hanover (NH)",
  "townPop": 11870,
  "townPopYear": "2020",
  "townNote": "rural Upper Valley; nearest city is 2 hours away",
  "nature": 5,
  "beachMiles": 110
 },
 "Harvard": {
  "ratio": 7,
  "retention": 99,
  "townName": "Cambridge",
  "townPop": 118403,
  "townPopYear": "2020",
  "townNote": "across the river from Boston",
  "nature": 2,
  "beachMiles": 10
 },
 "Penn": {
  "ratio": 8,
  "retention": 98,
  "townName": "Philadelphia",
  "townPop": 1603797,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 60
 },
 "Princeton": {
  "ratio": 5,
  "retention": 97,
  "townName": "Princeton",
  "townPop": 30681,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 45
 },
 "Yale": {
  "ratio": 6,
  "retention": 99,
  "townName": "New Haven",
  "townPop": 134023,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 2,
  "beachMiles": 5
 },
 "Williams": {
  "ratio": 6,
  "retention": 97,
  "townName": "Williamstown",
  "townPop": 7513,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 5,
  "beachMiles": 150
 },
 "Amherst": {
  "ratio": 7,
  "retention": 97,
  "townName": "Amherst",
  "townPop": 39263,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 110
 },
 "Swarthmore": {
  "ratio": 8,
  "retention": 97,
  "townName": "Swarthmore",
  "townPop": 6543,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 70
 },
 "Pomona": {
  "ratio": 7,
  "retention": 96,
  "townName": "Claremont",
  "townPop": 37266,
  "townPopYear": "2020",
  "townNote": "Claremont, 35 miles east of downtown Los Angeles",
  "nature": 3,
  "beachMiles": 45
 },
 "Wellesley": {
  "ratio": 7,
  "retention": 96,
  "townName": "Wellesley",
  "townPop": 29550,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 25
 },
 "Bowdoin": {
  "ratio": 9,
  "retention": 98,
  "townName": "Brunswick",
  "townPop": 21756,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 8
 },
 "Carleton": {
  "ratio": 8,
  "retention": 96,
  "townName": "Northfield",
  "townPop": 20790,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 400
 },
 "Middlebury": {
  "ratio": 9,
  "retention": 94,
  "townName": "Middlebury",
  "townPop": 9152,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 5,
  "beachMiles": 180
 },
 "Davidson": {
  "ratio": 9,
  "retention": 95,
  "townName": "Davidson",
  "townPop": 15106,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 200
 },
 "Harvey Mudd": {
  "ratio": 8,
  "retention": 97,
  "townName": "Claremont",
  "townPop": 37266,
  "townPopYear": "2020",
  "townNote": "Claremont, 35 miles east of downtown Los Angeles",
  "nature": 3,
  "beachMiles": 45
 },
 "Claremont McKenna": {
  "ratio": 8,
  "retention": 96,
  "townName": "Claremont",
  "townPop": 37266,
  "townPopYear": "2020",
  "townNote": "Claremont, 35 miles east of downtown Los Angeles",
  "nature": 3,
  "beachMiles": 45
 },
 "Haverford": {
  "ratio": 8,
  "retention": 94,
  "townName": "Haverford Township",
  "townPop": 50431,
  "townPopYear": "2020",
  "townNote": "Main Line suburb of Philadelphia",
  "nature": 4,
  "beachMiles": 75
 },
 "Vassar": {
  "ratio": 8,
  "retention": 94,
  "townName": "Poughkeepsie",
  "townPop": 31577,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 90
 },
 "Grinnell": {
  "ratio": 9,
  "retention": 93,
  "townName": "Grinnell",
  "townPop": 9564,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 500
 },
 "Wesleyan": {
  "ratio": 7,
  "retention": 95,
  "townName": "Middletown",
  "townPop": 47717,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 25
 },
 "Scripps": {
  "ratio": 11,
  "retention": 88,
  "townName": "Claremont",
  "townPop": 37266,
  "townPopYear": "2020",
  "townNote": "Claremont, 35 miles east of downtown Los Angeles",
  "nature": 3,
  "beachMiles": 45
 },
 "Pitzer": {
  "ratio": 10,
  "retention": 94,
  "townName": "Claremont",
  "townPop": 37266,
  "townPopYear": "2020",
  "townNote": "Claremont, 35 miles east of downtown Los Angeles",
  "nature": 3,
  "beachMiles": 45
 },
 "Occidental": {
  "ratio": 9,
  "retention": 87,
  "townName": "Los Angeles",
  "townPop": 3898747,
  "townPopYear": "2020",
  "townNote": "Eagle Rock neighborhood of Los Angeles",
  "nature": 3,
  "beachMiles": 20
 },
 "Whitman": {
  "ratio": 10,
  "retention": 89,
  "townName": "Walla Walla",
  "townPop": 34060,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 3,
  "beachMiles": 250
 },
 "Reed": {
  "ratio": 9,
  "retention": 86,
  "townName": "Portland",
  "townPop": 652503,
  "townPopYear": "2020",
  "townNote": null,
  "nature": 4,
  "beachMiles": 80
 }
};
window.CAMPUS_PROFILE_META={
 "ratioSource": "IPEDS Fall Enrollment survey EF2023D, student-to-faculty ratio and full-time retention, fall 2023",
 "townSource": "2020 Census population via Wikidata",
 "natureSource": "4ward rating, rubric in build_profile.py",
 "beachSource": "approximate road miles to the nearest ocean beach, hand-entered"
};
