// generated by build_climate.py -- do not edit by hand
window.CLIMATE_CATEGORIES={
 "mild": "Mild year-round (coastal California)",
 "warm": "Warm and sunny, hot summers (inland California)",
 "humid": "Hot, humid summers; mild winters (South)",
 "seasons": "Four seasons, moderate winters (Mid-Atlantic, Upper South)",
 "cold": "Four seasons, cold and snowy winters",
 "pnw": "Cool, rainy winters; mild summers (Pacific Northwest)"
};
window.CAMPUS_CLIMATE={
 "Stanford": {
  "winterHigh": 59,
  "summerHigh": 82,
  "precipIn": 24,
  "snowIn": 0,
  "sunHours": 10.3,
  "rainDays": 45,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Caltech": {
  "winterHigh": 64,
  "summerHigh": 87,
  "precipIn": 28,
  "snowIn": 1,
  "sunHours": 10.8,
  "rainDays": 35,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "USC": {
  "winterHigh": 65,
  "summerHigh": 82,
  "precipIn": 20,
  "snowIn": 0,
  "sunHours": 10.1,
  "rainDays": 28,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Santa Clara": {
  "winterHigh": 60,
  "summerHigh": 84,
  "precipIn": 24,
  "snowIn": 1,
  "sunHours": 10.5,
  "rainDays": 45,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Loyola Marymount": {
  "winterHigh": 63,
  "summerHigh": 75,
  "precipIn": 20,
  "snowIn": 0,
  "sunHours": 10.1,
  "rainDays": 27,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "University of San Diego": {
  "winterHigh": 63,
  "summerHigh": 75,
  "precipIn": 15,
  "snowIn": 0,
  "sunHours": 10.2,
  "rainDays": 25,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Pepperdine": {
  "winterHigh": 63,
  "summerHigh": 80,
  "precipIn": 22,
  "snowIn": 0,
  "sunHours": 10.4,
  "rainDays": 29,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Chapman": {
  "winterHigh": 66,
  "summerHigh": 83,
  "precipIn": 17,
  "snowIn": 0,
  "sunHours": 10.5,
  "rainDays": 27,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "University of Portland": {
  "winterHigh": 47,
  "summerHigh": 81,
  "precipIn": 57,
  "snowIn": 20,
  "sunHours": 8.1,
  "rainDays": 117,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "Gonzaga": {
  "winterHigh": 37,
  "summerHigh": 83,
  "precipIn": 19,
  "snowIn": 31,
  "sunHours": 8.8,
  "rainDays": 58,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "MIT": {
  "winterHigh": 41,
  "summerHigh": 81,
  "precipIn": 48,
  "snowIn": 28,
  "sunHours": 8.6,
  "rainDays": 91,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "University of Chicago": {
  "winterHigh": 37,
  "summerHigh": 81,
  "precipIn": 45,
  "snowIn": 23,
  "sunHours": 8.6,
  "rainDays": 91,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Duke": {
  "winterHigh": 54,
  "summerHigh": 88,
  "precipIn": 47,
  "snowIn": 2,
  "sunHours": 9.2,
  "rainDays": 80,
  "category": "humid",
  "label": "Hot, humid summers; mild winters (South)"
 },
 "Northwestern": {
  "winterHigh": 37,
  "summerHigh": 79,
  "precipIn": 41,
  "snowIn": 27,
  "sunHours": 8.6,
  "rainDays": 91,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Johns Hopkins": {
  "winterHigh": 46,
  "summerHigh": 85,
  "precipIn": 56,
  "snowIn": 8,
  "sunHours": 8.9,
  "rainDays": 105,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "Rice": {
  "winterHigh": 66,
  "summerHigh": 93,
  "precipIn": 66,
  "snowIn": 0,
  "sunHours": 9.3,
  "rainDays": 101,
  "category": "humid",
  "label": "Hot, humid summers; mild winters (South)"
 },
 "Vanderbilt": {
  "winterHigh": 52,
  "summerHigh": 89,
  "precipIn": 67,
  "snowIn": 6,
  "sunHours": 9.1,
  "rainDays": 111,
  "category": "humid",
  "label": "Hot, humid summers; mild winters (South)"
 },
 "Notre Dame": {
  "winterHigh": 38,
  "summerHigh": 81,
  "precipIn": 43,
  "snowIn": 34,
  "sunHours": 8.2,
  "rainDays": 93,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Carnegie Mellon": {
  "winterHigh": 43,
  "summerHigh": 82,
  "precipIn": 50,
  "snowIn": 16,
  "sunHours": 8.2,
  "rainDays": 107,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "Georgetown": {
  "winterHigh": 48,
  "summerHigh": 86,
  "precipIn": 51,
  "snowIn": 7,
  "sunHours": 8.8,
  "rainDays": 99,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "Tufts": {
  "winterHigh": 41,
  "summerHigh": 80,
  "precipIn": 49,
  "snowIn": 30,
  "sunHours": 8.6,
  "rainDays": 95,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Boston College": {
  "winterHigh": 41,
  "summerHigh": 81,
  "precipIn": 48,
  "snowIn": 28,
  "sunHours": 8.6,
  "rainDays": 91,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Northeastern": {
  "winterHigh": 41,
  "summerHigh": 81,
  "precipIn": 48,
  "snowIn": 28,
  "sunHours": 8.6,
  "rainDays": 91,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Boston University": {
  "winterHigh": 41,
  "summerHigh": 81,
  "precipIn": 48,
  "snowIn": 28,
  "sunHours": 8.6,
  "rainDays": 91,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "NYU": {
  "winterHigh": 44,
  "summerHigh": 84,
  "precipIn": 55,
  "snowIn": 15,
  "sunHours": 8.8,
  "rainDays": 98,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "Wake Forest": {
  "winterHigh": 52,
  "summerHigh": 88,
  "precipIn": 41,
  "snowIn": 4,
  "sunHours": 9.3,
  "rainDays": 85,
  "category": "humid",
  "label": "Hot, humid summers; mild winters (South)"
 },
 "Case Western Reserve": {
  "winterHigh": 39,
  "summerHigh": 78,
  "precipIn": 50,
  "snowIn": 38,
  "sunHours": 8.4,
  "rainDays": 118,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Tulane": {
  "winterHigh": 65,
  "summerHigh": 91,
  "precipIn": 64,
  "snowIn": 0,
  "sunHours": 9.7,
  "rainDays": 115,
  "category": "humid",
  "label": "Hot, humid summers; mild winters (South)"
 },
 "Emory": {
  "winterHigh": 56,
  "summerHigh": 88,
  "precipIn": 57,
  "snowIn": 1,
  "sunHours": 9.1,
  "rainDays": 100,
  "category": "humid",
  "label": "Hot, humid summers; mild winters (South)"
 },
 "Williams": {
  "winterHigh": 36,
  "summerHigh": 78,
  "precipIn": 54,
  "snowIn": 68,
  "sunHours": 8.1,
  "rainDays": 110,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Amherst": {
  "winterHigh": 39,
  "summerHigh": 81,
  "precipIn": 52,
  "snowIn": 40,
  "sunHours": 8.4,
  "rainDays": 96,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Swarthmore": {
  "winterHigh": 46,
  "summerHigh": 86,
  "precipIn": 49,
  "snowIn": 9,
  "sunHours": 8.7,
  "rainDays": 94,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "Pomona": {
  "winterHigh": 62,
  "summerHigh": 90,
  "precipIn": 33,
  "snowIn": 6,
  "sunHours": 10.7,
  "rainDays": 44,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Wellesley": {
  "winterHigh": 41,
  "summerHigh": 82,
  "precipIn": 49,
  "snowIn": 30,
  "sunHours": 8.5,
  "rainDays": 94,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Bowdoin": {
  "winterHigh": 36,
  "summerHigh": 76,
  "precipIn": 52,
  "snowIn": 46,
  "sunHours": 8.5,
  "rainDays": 95,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Carleton": {
  "winterHigh": 29,
  "summerHigh": 81,
  "precipIn": 35,
  "snowIn": 35,
  "sunHours": 8.7,
  "rainDays": 74,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Middlebury": {
  "winterHigh": 35,
  "summerHigh": 79,
  "precipIn": 47,
  "snowIn": 54,
  "sunHours": 8.0,
  "rainDays": 98,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Davidson": {
  "winterHigh": 53,
  "summerHigh": 87,
  "precipIn": 44,
  "snowIn": 2,
  "sunHours": 9.3,
  "rainDays": 81,
  "category": "humid",
  "label": "Hot, humid summers; mild winters (South)"
 },
 "Harvey Mudd": {
  "winterHigh": 62,
  "summerHigh": 89,
  "precipIn": 33,
  "snowIn": 6,
  "sunHours": 10.7,
  "rainDays": 44,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Claremont McKenna": {
  "winterHigh": 62,
  "summerHigh": 90,
  "precipIn": 33,
  "snowIn": 6,
  "sunHours": 10.7,
  "rainDays": 44,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Haverford": {
  "winterHigh": 45,
  "summerHigh": 85,
  "precipIn": 50,
  "snowIn": 11,
  "sunHours": 8.7,
  "rainDays": 92,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "Vassar": {
  "winterHigh": 41,
  "summerHigh": 83,
  "precipIn": 49,
  "snowIn": 30,
  "sunHours": 8.6,
  "rainDays": 93,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Grinnell": {
  "winterHigh": 35,
  "summerHigh": 82,
  "precipIn": 34,
  "snowIn": 24,
  "sunHours": 9.1,
  "rainDays": 68,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Wesleyan": {
  "winterHigh": 41,
  "summerHigh": 81,
  "precipIn": 53,
  "snowIn": 22,
  "sunHours": 8.6,
  "rainDays": 97,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Scripps": {
  "winterHigh": 62,
  "summerHigh": 90,
  "precipIn": 33,
  "snowIn": 6,
  "sunHours": 10.7,
  "rainDays": 44,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Pitzer": {
  "winterHigh": 62,
  "summerHigh": 90,
  "precipIn": 33,
  "snowIn": 6,
  "sunHours": 10.7,
  "rainDays": 44,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Occidental": {
  "winterHigh": 64,
  "summerHigh": 87,
  "precipIn": 28,
  "snowIn": 1,
  "sunHours": 10.8,
  "rainDays": 35,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Whitman": {
  "winterHigh": 43,
  "summerHigh": 88,
  "precipIn": 21,
  "snowIn": 17,
  "sunHours": 9.0,
  "rainDays": 61,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "Reed": {
  "winterHigh": 47,
  "summerHigh": 81,
  "precipIn": 59,
  "snowIn": 21,
  "sunHours": 8.0,
  "rainDays": 119,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "Brown": {
  "winterHigh": 42,
  "summerHigh": 82,
  "precipIn": 53,
  "snowIn": 25,
  "sunHours": 8.5,
  "rainDays": 97,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Columbia": {
  "winterHigh": 44,
  "summerHigh": 84,
  "precipIn": 55,
  "snowIn": 16,
  "sunHours": 8.7,
  "rainDays": 96,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "Cornell": {
  "winterHigh": 37,
  "summerHigh": 79,
  "precipIn": 47,
  "snowIn": 52,
  "sunHours": 8.0,
  "rainDays": 108,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Dartmouth": {
  "winterHigh": 34,
  "summerHigh": 78,
  "precipIn": 44,
  "snowIn": 63,
  "sunHours": 8.2,
  "rainDays": 97,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Harvard": {
  "winterHigh": 41,
  "summerHigh": 81,
  "precipIn": 48,
  "snowIn": 28,
  "sunHours": 8.6,
  "rainDays": 91,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Penn": {
  "winterHigh": 46,
  "summerHigh": 86,
  "precipIn": 48,
  "snowIn": 10,
  "sunHours": 8.8,
  "rainDays": 89,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "Princeton": {
  "winterHigh": 45,
  "summerHigh": 86,
  "precipIn": 50,
  "snowIn": 12,
  "sunHours": 8.7,
  "rainDays": 95,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "Yale": {
  "winterHigh": 42,
  "summerHigh": 80,
  "precipIn": 54,
  "snowIn": 18,
  "sunHours": 8.8,
  "rainDays": 93,
  "category": "seasons",
  "label": "Four seasons, moderate winters (Mid-Atlantic, Upper South)"
 },
 "UC Berkeley": {
  "winterHigh": 57,
  "summerHigh": 73,
  "precipIn": 29,
  "snowIn": 1,
  "sunHours": 10.1,
  "rainDays": 52,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "UC Davis": {
  "winterHigh": 58,
  "summerHigh": 96,
  "precipIn": 23,
  "snowIn": 1,
  "sunHours": 10.4,
  "rainDays": 45,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "UC Irvine": {
  "winterHigh": 65,
  "summerHigh": 80,
  "precipIn": 20,
  "snowIn": 0,
  "sunHours": 10.6,
  "rainDays": 32,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "UCLA": {
  "winterHigh": 65,
  "summerHigh": 80,
  "precipIn": 21,
  "snowIn": 0,
  "sunHours": 10.1,
  "rainDays": 28,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "UC Merced": {
  "winterHigh": 58,
  "summerHigh": 99,
  "precipIn": 21,
  "snowIn": 1,
  "sunHours": 10.6,
  "rainDays": 41,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "UC Riverside": {
  "winterHigh": 63,
  "summerHigh": 93,
  "precipIn": 16,
  "snowIn": 1,
  "sunHours": 10.7,
  "rainDays": 31,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "UC San Diego": {
  "winterHigh": 63,
  "summerHigh": 75,
  "precipIn": 15,
  "snowIn": 0,
  "sunHours": 10.1,
  "rainDays": 26,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "UC Santa Barbara": {
  "winterHigh": 65,
  "summerHigh": 83,
  "precipIn": 26,
  "snowIn": 1,
  "sunHours": 10.7,
  "rainDays": 33,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "UC Santa Cruz": {
  "winterHigh": 59,
  "summerHigh": 75,
  "precipIn": 38,
  "snowIn": 1,
  "sunHours": 10.1,
  "rainDays": 47,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "CSU Bakersfield": {
  "winterHigh": 61,
  "summerHigh": 102,
  "precipIn": 12,
  "snowIn": 1,
  "sunHours": 11.0,
  "rainDays": 27,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "CSU Channel Islands": {
  "winterHigh": 63,
  "summerHigh": 74,
  "precipIn": 19,
  "snowIn": 0,
  "sunHours": 10.6,
  "rainDays": 28,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Chico State": {
  "winterHigh": 58,
  "summerHigh": 101,
  "precipIn": 31,
  "snowIn": 1,
  "sunHours": 10.2,
  "rainDays": 54,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "CSU Dominguez Hills": {
  "winterHigh": 66,
  "summerHigh": 82,
  "precipIn": 18,
  "snowIn": 0,
  "sunHours": 10.0,
  "rainDays": 25,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Cal State East Bay": {
  "winterHigh": 56,
  "summerHigh": 70,
  "precipIn": 29,
  "snowIn": 1,
  "sunHours": 10.0,
  "rainDays": 52,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Fresno State": {
  "winterHigh": 59,
  "summerHigh": 101,
  "precipIn": 20,
  "snowIn": 1,
  "sunHours": 10.7,
  "rainDays": 37,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Cal State Fullerton": {
  "winterHigh": 66,
  "summerHigh": 84,
  "precipIn": 21,
  "snowIn": 0,
  "sunHours": 10.4,
  "rainDays": 28,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Cal Poly Humboldt": {
  "winterHigh": 55,
  "summerHigh": 66,
  "precipIn": 67,
  "snowIn": 16,
  "sunHours": 9.4,
  "rainDays": 91,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "Cal State Long Beach": {
  "winterHigh": 64,
  "summerHigh": 78,
  "precipIn": 18,
  "snowIn": 0,
  "sunHours": 10.2,
  "rainDays": 25,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Cal State LA": {
  "winterHigh": 65,
  "summerHigh": 87,
  "precipIn": 23,
  "snowIn": 0,
  "sunHours": 10.0,
  "rainDays": 31,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Cal State Monterey Bay": {
  "winterHigh": 61,
  "summerHigh": 70,
  "precipIn": 23,
  "snowIn": 1,
  "sunHours": 10.1,
  "rainDays": 45,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Cal State Northridge": {
  "winterHigh": 64,
  "summerHigh": 89,
  "precipIn": 24,
  "snowIn": 0,
  "sunHours": 10.6,
  "rainDays": 30,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Cal Poly Pomona": {
  "winterHigh": 64,
  "summerHigh": 90,
  "precipIn": 24,
  "snowIn": 1,
  "sunHours": 10.1,
  "rainDays": 33,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Sacramento State": {
  "winterHigh": 57,
  "summerHigh": 96,
  "precipIn": 28,
  "snowIn": 0,
  "sunHours": 10.3,
  "rainDays": 49,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Cal State San Bernardino": {
  "winterHigh": 62,
  "summerHigh": 93,
  "precipIn": 27,
  "snowIn": 3,
  "sunHours": 10.9,
  "rainDays": 39,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "San Diego State": {
  "winterHigh": 65,
  "summerHigh": 81,
  "precipIn": 16,
  "snowIn": 0,
  "sunHours": 10.2,
  "rainDays": 28,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "San Francisco State": {
  "winterHigh": 56,
  "summerHigh": 64,
  "precipIn": 27,
  "snowIn": 0,
  "sunHours": 10.1,
  "rainDays": 47,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "San José State": {
  "winterHigh": 60,
  "summerHigh": 84,
  "precipIn": 24,
  "snowIn": 1,
  "sunHours": 10.5,
  "rainDays": 45,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Cal Poly San Luis Obispo": {
  "winterHigh": 63,
  "summerHigh": 78,
  "precipIn": 27,
  "snowIn": 1,
  "sunHours": 10.7,
  "rainDays": 37,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Cal State San Marcos": {
  "winterHigh": 64,
  "summerHigh": 81,
  "precipIn": 19,
  "snowIn": 0,
  "sunHours": 10.4,
  "rainDays": 31,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Sonoma State": {
  "winterHigh": 59,
  "summerHigh": 82,
  "precipIn": 34,
  "snowIn": 2,
  "sunHours": 10.0,
  "rainDays": 49,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "Stanislaus State": {
  "winterHigh": 58,
  "summerHigh": 98,
  "precipIn": 21,
  "snowIn": 0,
  "sunHours": 10.5,
  "rainDays": 43,
  "category": "warm",
  "label": "Warm and sunny, hot summers (inland California)"
 },
 "Cal Poly Maritime Academy": {
  "winterHigh": 57,
  "summerHigh": 80,
  "precipIn": 25,
  "snowIn": 0,
  "sunHours": 10.2,
  "rainDays": 47,
  "category": "mild",
  "label": "Mild year-round (coastal California)"
 },
 "McGill": {
  "winterHigh": 28,
  "summerHigh": 77,
  "precipIn": 49,
  "snowIn": 60,
  "sunHours": 7.9,
  "rainDays": 103,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "UBC": {
  "winterHigh": 43,
  "summerHigh": 70,
  "precipIn": 67,
  "snowIn": 37,
  "sunHours": 7.8,
  "rainDays": 130,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "University of Toronto": {
  "winterHigh": 35,
  "summerHigh": 77,
  "precipIn": 37,
  "snowIn": 36,
  "sunHours": 8.4,
  "rainDays": 91,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Concordia": {
  "winterHigh": 28,
  "summerHigh": 77,
  "precipIn": 49,
  "snowIn": 60,
  "sunHours": 7.9,
  "rainDays": 103,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "McMaster": {
  "winterHigh": 36,
  "summerHigh": 78,
  "precipIn": 36,
  "snowIn": 36,
  "sunHours": 8.3,
  "rainDays": 86,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "Memorial": {
  "winterHigh": 35,
  "summerHigh": 66,
  "precipIn": 63,
  "snowIn": 84,
  "sunHours": 5.6,
  "rainDays": 124,
  "category": "cold",
  "label": "Four seasons, cold and snowy winters"
 },
 "St Andrews": {
  "winterHigh": 46,
  "summerHigh": 65,
  "precipIn": 37,
  "snowIn": 6,
  "sunHours": 7.2,
  "rainDays": 103,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "Edinburgh": {
  "winterHigh": 45,
  "summerHigh": 64,
  "precipIn": 41,
  "snowIn": 6,
  "sunHours": 7.1,
  "rainDays": 115,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "Glasgow": {
  "winterHigh": 45,
  "summerHigh": 65,
  "precipIn": 52,
  "snowIn": 7,
  "sunHours": 6.5,
  "rainDays": 144,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "Trinity College Dublin": {
  "winterHigh": 49,
  "summerHigh": 66,
  "precipIn": 39,
  "snowIn": 2,
  "sunHours": 7.3,
  "rainDays": 107,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "University College Dublin": {
  "winterHigh": 49,
  "summerHigh": 66,
  "precipIn": 39,
  "snowIn": 2,
  "sunHours": 7.3,
  "rainDays": 107,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "University of Amsterdam": {
  "winterHigh": 46,
  "summerHigh": 71,
  "precipIn": 42,
  "snowIn": 9,
  "sunHours": 7.8,
  "rainDays": 117,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "Maastricht": {
  "winterHigh": 46,
  "summerHigh": 74,
  "precipIn": 41,
  "snowIn": 9,
  "sunHours": 7.4,
  "rainDays": 114,
  "category": "pnw",
  "label": "Cool, rainy winters; mild summers (Pacific Northwest)"
 }
};
window.CAMPUS_CLIMATE_META={
 "source": "Open-Meteo historical weather archive (ERA5), daily values 2022-2024 at campus coordinates",
 "url": "https://open-meteo.com/",
 "categories": {
  "mild": "Mild year-round (coastal California)",
  "warm": "Warm and sunny, hot summers (inland California)",
  "humid": "Hot, humid summers; mild winters (South)",
  "seasons": "Four seasons, moderate winters (Mid-Atlantic, Upper South)",
  "cold": "Four seasons, cold and snowy winters",
  "pnw": "Cool, rainy winters; mild summers (Pacific Northwest)"
 },
 "rules": "pnw: >= 35 in rain, summer highs <= 82F, winter highs 44-57F; cold: snow >= 20 in/yr or winter highs under 42F; seasons: snow >= 6 in or winter highs under 50F; humid: summer highs >= 85F with >= 40 in rain; mild: winter highs >= 55F, summer highs <= 85F, under 2 in snow; warm: summer highs over 85F with under 40 in rain; otherwise four seasons, moderate winters"
};
