// generated by build_mountains.py -- do not edit by hand
window.CAMPUS_MOUNTAINS={
 "Amherst": {
  "campusElevFt": 325,
  "mountainMiles": 18,
  "mountainRelief": 1024,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 2894,
  "label": "Mountains within a short drive"
 },
 "Boston College": {
  "campusElevFt": 180,
  "mountainMiles": 50,
  "mountainRelief": 1017,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 2434,
  "label": "Mountains within an hour or so"
 },
 "Boston University": {
  "campusElevFt": 36,
  "mountainMiles": 50,
  "mountainRelief": 1086,
  "bearing": "WNW",
  "bigMountainMiles": null,
  "maxRelief": 2215,
  "label": "Mountains within an hour or so"
 },
 "Bowdoin": {
  "campusElevFt": 85,
  "mountainMiles": 70,
  "mountainRelief": 3796,
  "bearing": "WNW",
  "bigMountainMiles": 70,
  "maxRelief": 3796,
  "label": "Mountains within an hour or so"
 },
 "Brown": {
  "campusElevFt": 121,
  "mountainMiles": 70,
  "mountainRelief": 1270,
  "bearing": "NNW",
  "bigMountainMiles": null,
  "maxRelief": 1808,
  "label": "Mountains within an hour or so"
 },
 "CSU Bakersfield": {
  "campusElevFt": 390,
  "mountainMiles": 25,
  "mountainRelief": 2923,
  "bearing": "ENE",
  "bigMountainMiles": 35,
  "maxRelief": 11663,
  "label": "Mountains within a short drive"
 },
 "CSU Channel Islands": {
  "campusElevFt": 46,
  "mountainMiles": 3,
  "mountainRelief": 1299,
  "bearing": "S",
  "bigMountainMiles": 25,
  "maxRelief": 7625,
  "label": "Mountains at the edge of campus"
 },
 "CSU Dominguez Hills": {
  "campusElevFt": 95,
  "mountainMiles": 25,
  "mountainRelief": 2628,
  "bearing": "NNE",
  "bigMountainMiles": 35,
  "maxRelief": 5912,
  "label": "Mountains within a short drive"
 },
 "Cal Poly Humboldt": {
  "campusElevFt": 121,
  "mountainMiles": 5,
  "mountainRelief": 1175,
  "bearing": "SE",
  "bigMountainMiles": 18,
  "maxRelief": 5988,
  "label": "Mountains at the edge of campus"
 },
 "Cal Poly Maritime Academy": {
  "campusElevFt": 52,
  "mountainMiles": 12,
  "mountainRelief": 1165,
  "bearing": "S",
  "bigMountainMiles": 100,
  "maxRelief": 4068,
  "label": "Mountains a few minutes away"
 },
 "Cal Poly Pomona": {
  "campusElevFt": 719,
  "mountainMiles": 8,
  "mountainRelief": 1952,
  "bearing": "N",
  "bigMountainMiles": 12,
  "maxRelief": 6542,
  "label": "Mountains a few minutes away"
 },
 "Cal Poly San Luis Obispo": {
  "campusElevFt": 374,
  "mountainMiles": 3,
  "mountainRelief": 1394,
  "bearing": "ENE",
  "bigMountainMiles": 25,
  "maxRelief": 4606,
  "label": "Mountains at the edge of campus"
 },
 "Cal State East Bay": {
  "campusElevFt": 512,
  "mountainMiles": 5,
  "mountainRelief": 1161,
  "bearing": "ESE",
  "bigMountainMiles": 100,
  "maxRelief": 3205,
  "label": "Mountains at the edge of campus"
 },
 "Cal State Fullerton": {
  "campusElevFt": 253,
  "mountainMiles": 8,
  "mountainRelief": 1001,
  "bearing": "ENE",
  "bigMountainMiles": 25,
  "maxRelief": 7264,
  "label": "Mountains a few minutes away"
 },
 "Cal State LA": {
  "campusElevFt": 479,
  "mountainMiles": 12,
  "mountainRelief": 3583,
  "bearing": "NNE",
  "bigMountainMiles": 12,
  "maxRelief": 8209,
  "label": "Mountains a few minutes away"
 },
 "Cal State Long Beach": {
  "campusElevFt": 49,
  "mountainMiles": 25,
  "mountainRelief": 1093,
  "bearing": "E",
  "bigMountainMiles": 35,
  "maxRelief": 5098,
  "label": "Mountains within a short drive"
 },
 "Cal State Monterey Bay": {
  "campusElevFt": 236,
  "mountainMiles": 12,
  "mountainRelief": 1959,
  "bearing": "SE",
  "bigMountainMiles": 18,
  "maxRelief": 3802,
  "label": "Mountains a few minutes away"
 },
 "Cal State Northridge": {
  "campusElevFt": 860,
  "mountainMiles": 5,
  "mountainRelief": 1572,
  "bearing": "NNW",
  "bigMountainMiles": 18,
  "maxRelief": 6424,
  "label": "Mountains at the edge of campus"
 },
 "Cal State San Bernardino": {
  "campusElevFt": 1506,
  "mountainMiles": 3,
  "mountainRelief": 2133,
  "bearing": "N",
  "bigMountainMiles": 5,
  "maxRelief": 6936,
  "label": "In the mountains"
 },
 "Cal State San Marcos": {
  "campusElevFt": 741,
  "mountainMiles": 18,
  "mountainRelief": 2766,
  "bearing": "ENE",
  "bigMountainMiles": 25,
  "maxRelief": 4731,
  "label": "Mountains within a short drive"
 },
 "Caltech": {
  "campusElevFt": 764,
  "mountainMiles": 5,
  "mountainRelief": 2198,
  "bearing": "NE",
  "bigMountainMiles": 8,
  "maxRelief": 9232,
  "label": "In the mountains"
 },
 "Carleton": {
  "campusElevFt": 945,
  "mountainMiles": null,
  "mountainRelief": null,
  "bearing": null,
  "bigMountainMiles": null,
  "maxRelief": 423,
  "label": "Flat country; no high ground nearby"
 },
 "Carnegie Mellon": {
  "campusElevFt": 961,
  "mountainMiles": 35,
  "mountainRelief": 1014,
  "bearing": "ESE",
  "bigMountainMiles": null,
  "maxRelief": 1611,
  "label": "Mountains within a short drive"
 },
 "Case Western Reserve": {
  "campusElevFt": 686,
  "mountainMiles": null,
  "mountainRelief": null,
  "bearing": null,
  "bigMountainMiles": null,
  "maxRelief": 768,
  "label": "Flat country; no high ground nearby"
 },
 "Chapman": {
  "campusElevFt": 226,
  "mountainMiles": 12,
  "mountainRelief": 2051,
  "bearing": "ENE",
  "bigMountainMiles": 25,
  "maxRelief": 7963,
  "label": "Mountains a few minutes away"
 },
 "Chico State": {
  "campusElevFt": 236,
  "mountainMiles": 8,
  "mountainRelief": 1063,
  "bearing": "NE",
  "bigMountainMiles": 18,
  "maxRelief": 6158,
  "label": "Mountains a few minutes away"
 },
 "Claremont McKenna": {
  "campusElevFt": 1243,
  "mountainMiles": 5,
  "mountainRelief": 2946,
  "bearing": "N",
  "bigMountainMiles": 8,
  "maxRelief": 9849,
  "label": "In the mountains"
 },
 "Columbia": {
  "campusElevFt": 154,
  "mountainMiles": 35,
  "mountainRelief": 1096,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 1762,
  "label": "Mountains within a short drive"
 },
 "Cornell": {
  "campusElevFt": 778,
  "mountainMiles": 50,
  "mountainRelief": 1493,
  "bearing": "SSW",
  "bigMountainMiles": null,
  "maxRelief": 1493,
  "label": "Mountains within an hour or so"
 },
 "Dartmouth": {
  "campusElevFt": 538,
  "mountainMiles": 8,
  "mountainRelief": 1293,
  "bearing": "ENE",
  "bigMountainMiles": 50,
  "maxRelief": 3064,
  "label": "Mountains a few minutes away"
 },
 "Davidson": {
  "campusElevFt": 837,
  "mountainMiles": 70,
  "mountainRelief": 2448,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 2448,
  "label": "Mountains within an hour or so"
 },
 "Duke": {
  "campusElevFt": 417,
  "mountainMiles": 100,
  "mountainRelief": 2254,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 2254,
  "label": "High ground within a long drive"
 },
 "Emory": {
  "campusElevFt": 942,
  "mountainMiles": 50,
  "mountainRelief": 1572,
  "bearing": "N",
  "bigMountainMiles": null,
  "maxRelief": 2766,
  "label": "Mountains within an hour or so"
 },
 "Fresno State": {
  "campusElevFt": 322,
  "mountainMiles": 18,
  "mountainRelief": 1352,
  "bearing": "ENE",
  "bigMountainMiles": 25,
  "maxRelief": 11063,
  "label": "Mountains within a short drive"
 },
 "Georgetown": {
  "campusElevFt": 125,
  "mountainMiles": 100,
  "mountainRelief": 2198,
  "bearing": "W",
  "bigMountainMiles": null,
  "maxRelief": 2198,
  "label": "High ground within a long drive"
 },
 "Gonzaga": {
  "campusElevFt": 1916,
  "mountainMiles": 8,
  "mountainRelief": 1184,
  "bearing": "SE",
  "bigMountainMiles": 100,
  "maxRelief": 4190,
  "label": "Mountains a few minutes away"
 },
 "Grinnell": {
  "campusElevFt": 1024,
  "mountainMiles": null,
  "mountainRelief": null,
  "bearing": null,
  "bigMountainMiles": null,
  "maxRelief": 276,
  "label": "Flat country; no high ground nearby"
 },
 "Harvard": {
  "campusElevFt": 43,
  "mountainMiles": 50,
  "mountainRelief": 1181,
  "bearing": "WNW",
  "bigMountainMiles": null,
  "maxRelief": 2011,
  "label": "Mountains within an hour or so"
 },
 "Harvey Mudd": {
  "campusElevFt": 1260,
  "mountainMiles": 5,
  "mountainRelief": 3343,
  "bearing": "N",
  "bigMountainMiles": 5,
  "maxRelief": 9505,
  "label": "In the mountains"
 },
 "Haverford": {
  "campusElevFt": 348,
  "mountainMiles": 100,
  "mountainRelief": 1175,
  "bearing": "N",
  "bigMountainMiles": null,
  "maxRelief": 1175,
  "label": "High ground within a long drive"
 },
 "Johns Hopkins": {
  "campusElevFt": 249,
  "mountainMiles": 50,
  "mountainRelief": 1398,
  "bearing": "WNW",
  "bigMountainMiles": null,
  "maxRelief": 1398,
  "label": "Mountains within an hour or so"
 },
 "Loyola Marymount": {
  "campusElevFt": 135,
  "mountainMiles": 12,
  "mountainRelief": 1214,
  "bearing": "NNW",
  "bigMountainMiles": 25,
  "maxRelief": 6299,
  "label": "Mountains a few minutes away"
 },
 "MIT": {
  "campusElevFt": 49,
  "mountainMiles": 50,
  "mountainRelief": 1076,
  "bearing": "WNW",
  "bigMountainMiles": null,
  "maxRelief": 2753,
  "label": "Mountains within an hour or so"
 },
 "Middlebury": {
  "campusElevFt": 433,
  "mountainMiles": 5,
  "mountainRelief": 1138,
  "bearing": "E",
  "bigMountainMiles": 35,
  "maxRelief": 3071,
  "label": "Mountains at the edge of campus"
 },
 "NYU": {
  "campusElevFt": 79,
  "mountainMiles": 35,
  "mountainRelief": 1086,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 1854,
  "label": "Mountains within a short drive"
 },
 "Northeastern": {
  "campusElevFt": 33,
  "mountainMiles": 50,
  "mountainRelief": 1050,
  "bearing": "WNW",
  "bigMountainMiles": null,
  "maxRelief": 1841,
  "label": "Mountains within an hour or so"
 },
 "Northwestern": {
  "campusElevFt": 620,
  "mountainMiles": null,
  "mountainRelief": null,
  "bearing": null,
  "bigMountainMiles": null,
  "maxRelief": 417,
  "label": "Flat country; no high ground nearby"
 },
 "Notre Dame": {
  "campusElevFt": 758,
  "mountainMiles": null,
  "mountainRelief": null,
  "bearing": null,
  "bigMountainMiles": null,
  "maxRelief": 272,
  "label": "Flat country; no high ground nearby"
 },
 "Occidental": {
  "campusElevFt": 577,
  "mountainMiles": 8,
  "mountainRelief": 2871,
  "bearing": "N",
  "bigMountainMiles": 12,
  "maxRelief": 8077,
  "label": "Mountains a few minutes away"
 },
 "Penn": {
  "campusElevFt": 95,
  "mountainMiles": 70,
  "mountainRelief": 1004,
  "bearing": "NNW",
  "bigMountainMiles": null,
  "maxRelief": 1470,
  "label": "Mountains within an hour or so"
 },
 "Pepperdine": {
  "campusElevFt": 361,
  "mountainMiles": 3,
  "mountainRelief": 1804,
  "bearing": "NE",
  "bigMountainMiles": 35,
  "maxRelief": 5043,
  "label": "Mountains at the edge of campus"
 },
 "Pitzer": {
  "campusElevFt": 1260,
  "mountainMiles": 5,
  "mountainRelief": 3235,
  "bearing": "N",
  "bigMountainMiles": 5,
  "maxRelief": 9987,
  "label": "In the mountains"
 },
 "Pomona": {
  "campusElevFt": 1194,
  "mountainMiles": 5,
  "mountainRelief": 2733,
  "bearing": "N",
  "bigMountainMiles": 8,
  "maxRelief": 9446,
  "label": "In the mountains"
 },
 "Princeton": {
  "campusElevFt": 180,
  "mountainMiles": 70,
  "mountainRelief": 1781,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 1781,
  "label": "Mountains within an hour or so"
 },
 "Reed": {
  "campusElevFt": 112,
  "mountainMiles": 18,
  "mountainRelief": 1056,
  "bearing": "NE",
  "bigMountainMiles": 35,
  "maxRelief": 6480,
  "label": "Mountains within a short drive"
 },
 "Rice": {
  "campusElevFt": 56,
  "mountainMiles": null,
  "mountainRelief": null,
  "bearing": null,
  "bigMountainMiles": null,
  "maxRelief": 456,
  "label": "Flat country; no high ground nearby"
 },
 "Sacramento State": {
  "campusElevFt": 75,
  "mountainMiles": 25,
  "mountainRelief": 1358,
  "bearing": "ENE",
  "bigMountainMiles": 50,
  "maxRelief": 8123,
  "label": "Mountains within a short drive"
 },
 "San Diego State": {
  "campusElevFt": 440,
  "mountainMiles": 18,
  "mountainRelief": 2474,
  "bearing": "SE",
  "bigMountainMiles": 35,
  "maxRelief": 6040,
  "label": "Mountains within a short drive"
 },
 "San Francisco State": {
  "campusElevFt": 125,
  "mountainMiles": 25,
  "mountainRelief": 1650,
  "bearing": "SSE",
  "bigMountainMiles": 100,
  "maxRelief": 4006,
  "label": "Mountains within a short drive"
 },
 "San José State": {
  "campusElevFt": 108,
  "mountainMiles": 8,
  "mountainRelief": 2224,
  "bearing": "E",
  "bigMountainMiles": 100,
  "maxRelief": 3622,
  "label": "Mountains a few minutes away"
 },
 "Santa Clara": {
  "campusElevFt": 95,
  "mountainMiles": 12,
  "mountainRelief": 3041,
  "bearing": "SW",
  "bigMountainMiles": 12,
  "maxRelief": 3678,
  "label": "Mountains a few minutes away"
 },
 "Scripps": {
  "campusElevFt": 1240,
  "mountainMiles": 5,
  "mountainRelief": 2989,
  "bearing": "N",
  "bigMountainMiles": 8,
  "maxRelief": 9675,
  "label": "In the mountains"
 },
 "Sonoma State": {
  "campusElevFt": 118,
  "mountainMiles": 5,
  "mountainRelief": 2106,
  "bearing": "E",
  "bigMountainMiles": 100,
  "maxRelief": 3990,
  "label": "Mountains at the edge of campus"
 },
 "Stanford": {
  "campusElevFt": 118,
  "mountainMiles": 8,
  "mountainRelief": 1959,
  "bearing": "W",
  "bigMountainMiles": 100,
  "maxRelief": 3412,
  "label": "Mountains a few minutes away"
 },
 "Stanislaus State": {
  "campusElevFt": 95,
  "mountainMiles": 25,
  "mountainRelief": 1070,
  "bearing": "WSW",
  "bigMountainMiles": 50,
  "maxRelief": 9833,
  "label": "Mountains within a short drive"
 },
 "Swarthmore": {
  "campusElevFt": 230,
  "mountainMiles": 100,
  "mountainRelief": 1148,
  "bearing": "N",
  "bigMountainMiles": null,
  "maxRelief": 1148,
  "label": "High ground within a long drive"
 },
 "Tufts": {
  "campusElevFt": 69,
  "mountainMiles": 50,
  "mountainRelief": 1145,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 2195,
  "label": "Mountains within an hour or so"
 },
 "Tulane": {
  "campusElevFt": 72,
  "mountainMiles": null,
  "mountainRelief": null,
  "bearing": null,
  "bigMountainMiles": null,
  "maxRelief": 328,
  "label": "Flat country; no high ground nearby"
 },
 "UC Berkeley": {
  "campusElevFt": 318,
  "mountainMiles": 12,
  "mountainRelief": 1453,
  "bearing": "ESE",
  "bigMountainMiles": 70,
  "maxRelief": 3940,
  "label": "Mountains a few minutes away"
 },
 "UC Davis": {
  "campusElevFt": 85,
  "mountainMiles": 18,
  "mountainRelief": 1037,
  "bearing": "W",
  "bigMountainMiles": 70,
  "maxRelief": 7467,
  "label": "Mountains within a short drive"
 },
 "UC Irvine": {
  "campusElevFt": 79,
  "mountainMiles": 12,
  "mountainRelief": 1260,
  "bearing": "ENE",
  "bigMountainMiles": 18,
  "maxRelief": 5741,
  "label": "Mountains a few minutes away"
 },
 "UC Merced": {
  "campusElevFt": 243,
  "mountainMiles": 18,
  "mountainRelief": 1165,
  "bearing": "NE",
  "bigMountainMiles": 35,
  "maxRelief": 10167,
  "label": "Mountains within a short drive"
 },
 "UC Riverside": {
  "campusElevFt": 1027,
  "mountainMiles": 3,
  "mountainRelief": 1457,
  "bearing": "E",
  "bigMountainMiles": 18,
  "maxRelief": 7605,
  "label": "Mountains at the edge of campus"
 },
 "UC San Diego": {
  "campusElevFt": 361,
  "mountainMiles": 18,
  "mountainRelief": 1811,
  "bearing": "ENE",
  "bigMountainMiles": 35,
  "maxRelief": 5440,
  "label": "Mountains within a short drive"
 },
 "UC Santa Barbara": {
  "campusElevFt": 56,
  "mountainMiles": 5,
  "mountainRelief": 1604,
  "bearing": "N",
  "bigMountainMiles": 12,
  "maxRelief": 6243,
  "label": "Mountains at the edge of campus"
 },
 "UC Santa Cruz": {
  "campusElevFt": 666,
  "mountainMiles": 12,
  "mountainRelief": 1503,
  "bearing": "NE",
  "bigMountainMiles": 50,
  "maxRelief": 3383,
  "label": "Mountains a few minutes away"
 },
 "UCLA": {
  "campusElevFt": 417,
  "mountainMiles": 12,
  "mountainRelief": 1440,
  "bearing": "W",
  "bigMountainMiles": 18,
  "maxRelief": 6398,
  "label": "Mountains a few minutes away"
 },
 "USC": {
  "campusElevFt": 213,
  "mountainMiles": 12,
  "mountainRelief": 1188,
  "bearing": "NNE",
  "bigMountainMiles": 18,
  "maxRelief": 6453,
  "label": "Mountains a few minutes away"
 },
 "University of Chicago": {
  "campusElevFt": 643,
  "mountainMiles": null,
  "mountainRelief": null,
  "bearing": null,
  "bigMountainMiles": null,
  "maxRelief": 446,
  "label": "Flat country; no high ground nearby"
 },
 "University of Portland": {
  "campusElevFt": 144,
  "mountainMiles": 18,
  "mountainRelief": 1302,
  "bearing": "ENE",
  "bigMountainMiles": 35,
  "maxRelief": 4984,
  "label": "Mountains within a short drive"
 },
 "University of San Diego": {
  "campusElevFt": 200,
  "mountainMiles": 18,
  "mountainRelief": 1273,
  "bearing": "NE",
  "bigMountainMiles": 35,
  "maxRelief": 5266,
  "label": "Mountains within a short drive"
 },
 "Vanderbilt": {
  "campusElevFt": 597,
  "mountainMiles": 50,
  "mountainRelief": 1473,
  "bearing": "ESE",
  "bigMountainMiles": null,
  "maxRelief": 1473,
  "label": "Mountains within an hour or so"
 },
 "Vassar": {
  "campusElevFt": 157,
  "mountainMiles": 25,
  "mountainRelief": 1250,
  "bearing": "W",
  "bigMountainMiles": null,
  "maxRelief": 2336,
  "label": "Mountains within a short drive"
 },
 "Wake Forest": {
  "campusElevFt": 938,
  "mountainMiles": 18,
  "mountainRelief": 1030,
  "bearing": "N",
  "bigMountainMiles": 100,
  "maxRelief": 3310,
  "label": "Mountains within a short drive"
 },
 "Wellesley": {
  "campusElevFt": 151,
  "mountainMiles": 70,
  "mountainRelief": 1260,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 2221,
  "label": "Mountains within an hour or so"
 },
 "Wesleyan": {
  "campusElevFt": 180,
  "mountainMiles": 35,
  "mountainRelief": 1220,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 1657,
  "label": "Mountains within a short drive"
 },
 "Whitman": {
  "campusElevFt": 978,
  "mountainMiles": 8,
  "mountainRelief": 1089,
  "bearing": "ESE",
  "bigMountainMiles": 18,
  "maxRelief": 4695,
  "label": "Mountains a few minutes away"
 },
 "Williams": {
  "campusElevFt": 702,
  "mountainMiles": 3,
  "mountainRelief": 1457,
  "bearing": "ENE",
  "bigMountainMiles": null,
  "maxRelief": 2093,
  "label": "Mountains at the edge of campus"
 },
 "Yale": {
  "campusElevFt": 59,
  "mountainMiles": 35,
  "mountainRelief": 1047,
  "bearing": "NNW",
  "bigMountainMiles": null,
  "maxRelief": 1932,
  "label": "Mountains within a short drive"
 },
 "McGill": {
  "campusElevFt": 144,
  "mountainMiles": 50,
  "mountainRelief": 1624,
  "bearing": "SSW",
  "bigMountainMiles": null,
  "maxRelief": 2438,
  "label": "Mountains within an hour or so"
 },
 "UBC": {
  "campusElevFt": 276,
  "mountainMiles": 8,
  "mountainRelief": 2543,
  "bearing": "NNE",
  "bigMountainMiles": 12,
  "maxRelief": 5994,
  "label": "Mountains a few minutes away"
 },
 "University of Toronto": {
  "campusElevFt": 364,
  "mountainMiles": 50,
  "mountainRelief": 1168,
  "bearing": "WNW",
  "bigMountainMiles": null,
  "maxRelief": 1759,
  "label": "Mountains within an hour or so"
 },
 "Concordia": {
  "campusElevFt": 220,
  "mountainMiles": 50,
  "mountainRelief": 1558,
  "bearing": "NNW",
  "bigMountainMiles": null,
  "maxRelief": 2185,
  "label": "Mountains within an hour or so"
 },
 "McMaster": {
  "campusElevFt": 285,
  "mountainMiles": 35,
  "mountainRelief": 1010,
  "bearing": "NNW",
  "bigMountainMiles": null,
  "maxRelief": 1575,
  "label": "Mountains within a short drive"
 },
 "Memorial": {
  "campusElevFt": 243,
  "mountainMiles": null,
  "mountainRelief": null,
  "bearing": null,
  "bigMountainMiles": null,
  "maxRelief": 495,
  "label": "Flat country; no high ground nearby"
 },
 "St Andrews": {
  "campusElevFt": 69,
  "mountainMiles": 18,
  "mountainRelief": 1076,
  "bearing": "WSW",
  "bigMountainMiles": null,
  "maxRelief": 2159,
  "label": "Mountains within a short drive"
 },
 "Edinburgh": {
  "campusElevFt": 312,
  "mountainMiles": 5,
  "mountainRelief": 1014,
  "bearing": "SSW",
  "bigMountainMiles": null,
  "maxRelief": 2142,
  "label": "Mountains at the edge of campus"
 },
 "Glasgow": {
  "campusElevFt": 112,
  "mountainMiles": 25,
  "mountainRelief": 1545,
  "bearing": "NW",
  "bigMountainMiles": null,
  "maxRelief": 2713,
  "label": "Mountains within a short drive"
 },
 "Trinity College Dublin": {
  "campusElevFt": 36,
  "mountainMiles": 8,
  "mountainRelief": 1342,
  "bearing": "SSW",
  "bigMountainMiles": null,
  "maxRelief": 2090,
  "label": "Mountains a few minutes away"
 },
 "University College Dublin": {
  "campusElevFt": 62,
  "mountainMiles": 5,
  "mountainRelief": 1188,
  "bearing": "SSW",
  "bigMountainMiles": null,
  "maxRelief": 2415,
  "label": "Mountains at the edge of campus"
 },
 "University of Amsterdam": {
  "campusElevFt": 49,
  "mountainMiles": null,
  "mountainRelief": null,
  "bearing": null,
  "bigMountainMiles": null,
  "maxRelief": 240,
  "label": "Flat country; no high ground nearby"
 },
 "Maastricht": {
  "campusElevFt": 184,
  "mountainMiles": 25,
  "mountainRelief": 1325,
  "bearing": "SE",
  "bigMountainMiles": null,
  "maxRelief": 1673,
  "label": "Mountains within a short drive"
 }
};
window.CAMPUS_MOUNTAINS_META={
 "source": "ASTER GDEM v3 elevation, sampled through the OpenTopoData API",
 "url": "https://www.opentopodata.org/datasets/aster/",
 "method": "For each campus, elevation is sampled on rings at 3, 5, 8, 12, 18, 25, 35, 50, 70, 100 miles, 16 compass bearings per ring. The reported distance is the nearest ring holding ground at least 1000 ft above the campus.",
 "notes": {
  "units": "Straight-line miles, not road miles. The beachMiles figure in campus_profile.js is road miles, so the two are not the same unit and should not be compared directly.",
  "precision": "Distances land on the sampled ring, so they are approximate. Sampling 16 bearings can step over a narrow ridge between spokes, which biases a reported distance long rather than short.",
  "thresholds": "1,000 ft above campus is the bar for 'mountains'; 3,000 ft marks serious relief. A campus already high up needs ground higher still, so elevation alone never qualifies a place."
 }
};
