// generated by fetch_diversity.py -- do not edit by hand
window.CAMPUS_DIVERSITY={
 "UC Berkeley": {
  "shares": {
   "white": 0.1979,
   "black": 0.0205,
   "hispanic": 0.221,
   "asian": 0.3545,
   "aian": 0.0013,
   "nhpi": 0.001,
   "two_or_more": 0.0678,
   "non_resident_alien": 0.0984,
   "unknown": 0.0376
  },
  "largest": "Asian",
  "largestPct": 35,
  "index": 75,
  "intl": 0.0984,
  "pell": 0.2864,
  "men": 0.4421
 },
 "UC Davis": {
  "shares": {
   "white": 0.1987,
   "black": 0.0169,
   "hispanic": 0.251,
   "asian": 0.3142,
   "aian": 0.0011,
   "nhpi": 0.0018,
   "two_or_more": 0.0659,
   "non_resident_alien": 0.1285,
   "unknown": 0.0218
  },
  "largest": "Asian",
  "largestPct": 31,
  "index": 77,
  "intl": 0.1285,
  "pell": 0.3135,
  "men": 0.4138
 },
 "UC Irvine": {
  "shares": {
   "white": 0.1277,
   "black": 0.0195,
   "hispanic": 0.2683,
   "asian": 0.3747,
   "aian": 0.0014,
   "nhpi": 0.0008,
   "two_or_more": 0.063,
   "non_resident_alien": 0.123,
   "unknown": 0.0217
  },
  "largest": "Asian",
  "largestPct": 37,
  "index": 74,
  "intl": 0.123,
  "pell": 0.361,
  "men": 0.439
 },
 "UCLA": {
  "shares": {
   "white": 0.2391,
   "black": 0.0337,
   "hispanic": 0.2424,
   "asian": 0.2954,
   "aian": 0.0013,
   "nhpi": 0.0017,
   "two_or_more": 0.0777,
   "non_resident_alien": 0.0769,
   "unknown": 0.0318
  },
  "largest": "Asian",
  "largestPct": 30,
  "index": 77,
  "intl": 0.0769,
  "pell": 0.2824,
  "men": 0.3964
 },
 "UC Merced": {
  "shares": {
   "white": 0.0922,
   "black": 0.0508,
   "hispanic": 0.5541,
   "asian": 0.2358,
   "aian": 0.0018,
   "nhpi": 0.0025,
   "two_or_more": 0.0459,
   "non_resident_alien": 0.005,
   "unknown": 0.0119
  },
  "largest": "Hispanic or Latino",
  "largestPct": 55,
  "index": 62,
  "intl": 0.005,
  "pell": 0.5889,
  "men": 0.548
 },
 "UC Riverside": {
  "shares": {
   "white": 0.1033,
   "black": 0.0354,
   "hispanic": 0.3989,
   "asian": 0.359,
   "aian": 0.0009,
   "nhpi": 0.0015,
   "two_or_more": 0.0489,
   "non_resident_alien": 0.037,
   "unknown": 0.0152
  },
  "largest": "Hispanic or Latino",
  "largestPct": 40,
  "index": 69,
  "intl": 0.037,
  "pell": 0.4695,
  "men": 0.474
 },
 "UC San Diego": {
  "shares": {
   "white": 0.1718,
   "black": 0.0163,
   "hispanic": 0.2651,
   "asian": 0.3464,
   "aian": 0.0007,
   "nhpi": 0.0006,
   "two_or_more": 0.0646,
   "non_resident_alien": 0.1113,
   "unknown": 0.0231
  },
  "largest": "Asian",
  "largestPct": 35,
  "index": 75,
  "intl": 0.1113,
  "pell": 0.342,
  "men": 0.4516
 },
 "UC Santa Barbara": {
  "shares": {
   "white": 0.3175,
   "black": 0.0197,
   "hispanic": 0.2721,
   "asian": 0.1791,
   "aian": 0.0012,
   "nhpi": 0.0005,
   "two_or_more": 0.0951,
   "non_resident_alien": 0.0876,
   "unknown": 0.0273
  },
  "largest": "White",
  "largestPct": 32,
  "index": 76,
  "intl": 0.0876,
  "pell": 0.2785,
  "men": 0.4245
 },
 "UC Santa Cruz": {
  "shares": {
   "white": 0.3056,
   "black": 0.0206,
   "hispanic": 0.2863,
   "asian": 0.2431,
   "aian": 0.0016,
   "nhpi": 0.0012,
   "two_or_more": 0.0886,
   "non_resident_alien": 0.0303,
   "unknown": 0.0227
  },
  "largest": "White",
  "largestPct": 31,
  "index": 74,
  "intl": 0.0303,
  "pell": 0.3157,
  "men": 0.4723
 },
 "CSU Bakersfield": {
  "shares": {
   "white": 0.1214,
   "black": 0.042,
   "hispanic": 0.6956,
   "asian": 0.0646,
   "aian": 0.0031,
   "nhpi": 0.0015,
   "two_or_more": 0.0218,
   "non_resident_alien": 0.0129,
   "unknown": 0.0371
  },
  "largest": "Hispanic or Latino",
  "largestPct": 70,
  "index": 46,
  "intl": 0.0129,
  "pell": 0.6065,
  "men": 0.3514
 },
 "CSU Channel Islands": {
  "shares": {
   "white": 0.2228,
   "black": 0.0227,
   "hispanic": 0.604,
   "asian": 0.0626,
   "aian": 0.002,
   "nhpi": 0.0018,
   "two_or_more": 0.0415,
   "non_resident_alien": 0.0088,
   "unknown": 0.0337
  },
  "largest": "Hispanic or Latino",
  "largestPct": 60,
  "index": 55,
  "intl": 0.0088,
  "pell": 0.466,
  "men": 0.3373
 },
 "Chico State": {
  "shares": {
   "white": 0.4106,
   "black": 0.0304,
   "hispanic": 0.3889,
   "asian": 0.0544,
   "aian": 0.0049,
   "nhpi": 0.0025,
   "two_or_more": 0.0608,
   "non_resident_alien": 0.0112,
   "unknown": 0.0363
  },
  "largest": "White",
  "largestPct": 41,
  "index": 65,
  "intl": 0.0112,
  "pell": 0.4252,
  "men": 0.4358
 },
 "CSU Dominguez Hills": {
  "shares": {
   "white": 0.0396,
   "black": 0.1261,
   "hispanic": 0.7084,
   "asian": 0.0691,
   "aian": 0.0002,
   "nhpi": 0.0018,
   "two_or_more": 0.0234,
   "non_resident_alien": 0.0086,
   "unknown": 0.0227
  },
  "largest": "Hispanic or Latino",
  "largestPct": 71,
  "index": 45,
  "intl": 0.0086,
  "pell": 0.6333,
  "men": 0.4022
 },
 "Cal State East Bay": {
  "shares": {
   "white": 0.1514,
   "black": 0.0942,
   "hispanic": 0.4098,
   "asian": 0.2157,
   "aian": 0.0018,
   "nhpi": 0.0092,
   "two_or_more": 0.0509,
   "non_resident_alien": 0.0247,
   "unknown": 0.0423
  },
  "largest": "Hispanic or Latino",
  "largestPct": 41,
  "index": 73,
  "intl": 0.0247,
  "pell": 0.444,
  "men": 0.4145
 },
 "Fresno State": {
  "shares": {
   "white": 0.145,
   "black": 0.0299,
   "hispanic": 0.6321,
   "asian": 0.1146,
   "aian": 0.0031,
   "nhpi": 0.001,
   "two_or_more": 0.0262,
   "non_resident_alien": 0.0224,
   "unknown": 0.0256
  },
  "largest": "Hispanic or Latino",
  "largestPct": 63,
  "index": 54,
  "intl": 0.0224,
  "pell": 0.5697,
  "men": 0.4158
 },
 "Cal State Fullerton": {
  "shares": {
   "white": 0.1323,
   "black": 0.025,
   "hispanic": 0.562,
   "asian": 0.2079,
   "aian": 0.0011,
   "nhpi": 0.0015,
   "two_or_more": 0.0379,
   "non_resident_alien": 0.0098,
   "unknown": 0.0225
  },
  "largest": "Hispanic or Latino",
  "largestPct": 56,
  "index": 60,
  "intl": 0.0098,
  "pell": 0.4807,
  "men": 0.4413
 },
 "Cal Poly Humboldt": {
  "shares": {
   "white": 0.5157,
   "black": 0.0255,
   "hispanic": 0.286,
   "asian": 0.0317,
   "aian": 0.0135,
   "nhpi": 0.0027,
   "two_or_more": 0.0748,
   "non_resident_alien": 0.003,
   "unknown": 0.047
  },
  "largest": "White",
  "largestPct": 52,
  "index": 61,
  "intl": 0.003,
  "pell": 0.4287,
  "men": 0.4563
 },
 "Cal State Long Beach": {
  "shares": {
   "white": 0.1441,
   "black": 0.0395,
   "hispanic": 0.5246,
   "asian": 0.1989,
   "aian": 0.0011,
   "nhpi": 0.0023,
   "two_or_more": 0.0485,
   "non_resident_alien": 0.0218,
   "unknown": 0.0192
  },
  "largest": "Hispanic or Latino",
  "largestPct": 52,
  "index": 65,
  "intl": 0.0218,
  "pell": 0.5018,
  "men": 0.4145
 },
 "Cal State LA": {
  "shares": {
   "white": 0.0374,
   "black": 0.0428,
   "hispanic": 0.7765,
   "asian": 0.0978,
   "aian": 0.0013,
   "nhpi": 0.0005,
   "two_or_more": 0.0155,
   "non_resident_alien": 0.0101,
   "unknown": 0.0181
  },
  "largest": "Hispanic or Latino",
  "largestPct": 78,
  "index": 36,
  "intl": 0.0101,
  "pell": 0.663,
  "men": 0.4434
 },
 "Cal State Monterey Bay": {
  "shares": {
   "white": 0.2619,
   "black": 0.0224,
   "hispanic": 0.5587,
   "asian": 0.0601,
   "aian": 0.0025,
   "nhpi": 0.0025,
   "two_or_more": 0.0565,
   "non_resident_alien": 0.0131,
   "unknown": 0.0223
  },
  "largest": "Hispanic or Latino",
  "largestPct": 56,
  "index": 59,
  "intl": 0.0131,
  "pell": 0.4317,
  "men": 0.4053
 },
 "Cal State Northridge": {
  "shares": {
   "white": 0.1802,
   "black": 0.0559,
   "hispanic": 0.5791,
   "asian": 0.0874,
   "aian": 0.001,
   "nhpi": 0.0013,
   "two_or_more": 0.0327,
   "non_resident_alien": 0.0286,
   "unknown": 0.0338
  },
  "largest": "Hispanic or Latino",
  "largestPct": 58,
  "index": 59,
  "intl": 0.0286,
  "pell": 0.5607,
  "men": 0.4712
 },
 "Cal Poly Pomona": {
  "shares": {
   "white": 0.1281,
   "black": 0.0241,
   "hispanic": 0.5525,
   "asian": 0.2182,
   "aian": 0.0011,
   "nhpi": 0.0014,
   "two_or_more": 0.0397,
   "non_resident_alien": 0.011,
   "unknown": 0.0239
  },
  "largest": "Hispanic or Latino",
  "largestPct": 55,
  "index": 61,
  "intl": 0.011,
  "pell": 0.4633,
  "men": 0.5623
 },
 "Sacramento State": {
  "shares": {
   "white": 0.2253,
   "black": 0.0693,
   "hispanic": 0.3836,
   "asian": 0.2087,
   "aian": 0.0032,
   "nhpi": 0.0095,
   "two_or_more": 0.0625,
   "non_resident_alien": 0.0155,
   "unknown": 0.0224
  },
  "largest": "Hispanic or Latino",
  "largestPct": 38,
  "index": 74,
  "intl": 0.0155,
  "pell": 0.4913,
  "men": 0.4497
 },
 "Cal State San Bernardino": {
  "shares": {
   "white": 0.0933,
   "black": 0.0556,
   "hispanic": 0.729,
   "asian": 0.0578,
   "aian": 0.0017,
   "nhpi": 0.0019,
   "two_or_more": 0.0259,
   "non_resident_alien": 0.0113,
   "unknown": 0.0235
  },
  "largest": "Hispanic or Latino",
  "largestPct": 73,
  "index": 43,
  "intl": 0.0113,
  "pell": 0.5762,
  "men": 0.3911
 },
 "San Diego State": {
  "shares": {
   "white": 0.338,
   "black": 0.0345,
   "hispanic": 0.3674,
   "asian": 0.1319,
   "aian": 0.0017,
   "nhpi": 0.0026,
   "two_or_more": 0.0749,
   "non_resident_alien": 0.0195,
   "unknown": 0.0295
  },
  "largest": "Hispanic or Latino",
  "largestPct": 37,
  "index": 71,
  "intl": 0.0195,
  "pell": 0.3174,
  "men": 0.4344
 },
 "San Francisco State": {
  "shares": {
   "white": 0.15,
   "black": 0.0653,
   "hispanic": 0.4008,
   "asian": 0.2343,
   "aian": 0.0017,
   "nhpi": 0.0059,
   "two_or_more": 0.0624,
   "non_resident_alien": 0.0371,
   "unknown": 0.0424
  },
  "largest": "Hispanic or Latino",
  "largestPct": 40,
  "index": 73,
  "intl": 0.0371,
  "pell": 0.4222,
  "men": 0.4634
 },
 "San José State": {
  "shares": {
   "white": 0.1235,
   "black": 0.0353,
   "hispanic": 0.325,
   "asian": 0.388,
   "aian": 0.0007,
   "nhpi": 0.0046,
   "two_or_more": 0.0538,
   "non_resident_alien": 0.0364,
   "unknown": 0.0326
  },
  "largest": "Asian",
  "largestPct": 39,
  "index": 70,
  "intl": 0.0364,
  "pell": 0.3524,
  "men": 0.5233
 },
 "Cal Poly San Luis Obispo": {
  "shares": {
   "white": 0.4759,
   "black": 0.0076,
   "hispanic": 0.2525,
   "asian": 0.1397,
   "aian": 0.0012,
   "nhpi": 0.002,
   "two_or_more": 0.0813,
   "non_resident_alien": 0.0072,
   "unknown": 0.0326
  },
  "largest": "White",
  "largestPct": 48,
  "index": 66,
  "intl": 0.0072,
  "pell": 0.1924,
  "men": 0.4919
 },
 "Cal State San Marcos": {
  "shares": {
   "white": 0.2433,
   "black": 0.0402,
   "hispanic": 0.5154,
   "asian": 0.0931,
   "aian": 0.003,
   "nhpi": 0.0031,
   "two_or_more": 0.0633,
   "non_resident_alien": 0.0082,
   "unknown": 0.0304
  },
  "largest": "Hispanic or Latino",
  "largestPct": 52,
  "index": 64,
  "intl": 0.0082,
  "pell": 0.4261,
  "men": 0.4254
 },
 "Sonoma State": {
  "shares": {
   "white": 0.3995,
   "black": 0.0294,
   "hispanic": 0.4243,
   "asian": 0.0451,
   "aian": 0.0037,
   "nhpi": 0.0029,
   "two_or_more": 0.0637,
   "non_resident_alien": 0.0043,
   "unknown": 0.0271
  },
  "largest": "Hispanic or Latino",
  "largestPct": 42,
  "index": 63,
  "intl": 0.0043,
  "pell": 0.3592,
  "men": 0.4042
 },
 "Stanislaus State": {
  "shares": {
   "white": 0.1696,
   "black": 0.0267,
   "hispanic": 0.6284,
   "asian": 0.0885,
   "aian": 0.0021,
   "nhpi": 0.0062,
   "two_or_more": 0.0322,
   "non_resident_alien": 0.005,
   "unknown": 0.0413
  },
  "largest": "Hispanic or Latino",
  "largestPct": 63,
  "index": 53,
  "intl": 0.005,
  "pell": 0.5519,
  "men": 0.3475
 },
 "Cal Poly Maritime Academy": {
  "shares": {
   "white": 0.4813,
   "black": 0.0386,
   "hispanic": 0.2214,
   "asian": 0.0908,
   "aian": 0.0062,
   "nhpi": 0.0124,
   "two_or_more": 0.092,
   "non_resident_alien": 0.0037,
   "unknown": 0.0535
  },
  "largest": "White",
  "largestPct": 48,
  "index": 67,
  "intl": 0.0037,
  "pell": 0.251,
  "men": 0.8197
 },
 "Brown": {
  "shares": {
   "white": 0.3292,
   "black": 0.0818,
   "hispanic": 0.1212,
   "asian": 0.2288,
   "aian": 0.0021,
   "nhpi": 0.0011,
   "two_or_more": 0.0794,
   "non_resident_alien": 0.1269,
   "unknown": 0.0295
  },
  "largest": "White",
  "largestPct": 33,
  "index": 78,
  "intl": 0.1269,
  "pell": 0.1384,
  "men": 0.4997
 },
 "Columbia": {
  "shares": {
   "white": 0.287,
   "black": 0.0751,
   "hispanic": 0.1539,
   "asian": 0.1871,
   "aian": 0.0026,
   "nhpi": 0.0019,
   "two_or_more": 0.0625,
   "non_resident_alien": 0.1973,
   "unknown": 0.0327
  },
  "largest": "White",
  "largestPct": 29,
  "index": 80,
  "intl": 0.1973,
  "pell": 0.2271,
  "men": 0.502
 },
 "Cornell": {
  "shares": {
   "white": 0.3101,
   "black": 0.0684,
   "hispanic": 0.1316,
   "asian": 0.2676,
   "aian": 0.0018,
   "nhpi": 0.0016,
   "two_or_more": 0.0594,
   "non_resident_alien": 0.0955,
   "unknown": 0.0641
  },
  "largest": "White",
  "largestPct": 31,
  "index": 77,
  "intl": 0.0955,
  "pell": 0.1841,
  "men": 0.4544
 },
 "Dartmouth": {
  "shares": {
   "white": 0.4404,
   "black": 0.0623,
   "hispanic": 0.0991,
   "asian": 0.1306,
   "aian": 0.0112,
   "nhpi": 0,
   "two_or_more": 0.076,
   "non_resident_alien": 0.1508,
   "unknown": 0.0295
  },
  "largest": "White",
  "largestPct": 44,
  "index": 73,
  "intl": 0.1508,
  "pell": 0.1435,
  "men": 0.5177
 },
 "Harvard": {
  "shares": {
   "white": 0.3085,
   "black": 0.0887,
   "hispanic": 0.1187,
   "asian": 0.224,
   "aian": 0.0033,
   "nhpi": 0.002,
   "two_or_more": 0.0745,
   "non_resident_alien": 0.1459,
   "unknown": 0.0345
  },
  "largest": "White",
  "largestPct": 31,
  "index": 79,
  "intl": 0.1459,
  "pell": 0.1643,
  "men": 0.4623
 },
 "Penn": {
  "shares": {
   "white": 0.2738,
   "black": 0.0904,
   "hispanic": 0.1134,
   "asian": 0.2839,
   "aian": 0.0016,
   "nhpi": 0.0003,
   "two_or_more": 0.0527,
   "non_resident_alien": 0.1259,
   "unknown": 0.0579
  },
  "largest": "Asian",
  "largestPct": 28,
  "index": 78,
  "intl": 0.1259,
  "pell": 0.1653,
  "men": 0.4499
 },
 "Princeton": {
  "shares": {
   "white": 0.3365,
   "black": 0.0874,
   "hispanic": 0.1005,
   "asian": 0.2345,
   "aian": 0.0016,
   "nhpi": 0.0005,
   "two_or_more": 0.072,
   "non_resident_alien": 0.1263,
   "unknown": 0.0406
  },
  "largest": "White",
  "largestPct": 34,
  "index": 77,
  "intl": 0.1263,
  "pell": 0.1924,
  "men": 0.4962
 },
 "Yale": {
  "shares": {
   "white": 0.3122,
   "black": 0.0929,
   "hispanic": 0.1659,
   "asian": 0.2194,
   "aian": 0.004,
   "nhpi": 0.0016,
   "two_or_more": 0.0709,
   "non_resident_alien": 0.1116,
   "unknown": 0.0215
  },
  "largest": "White",
  "largestPct": 31,
  "index": 79,
  "intl": 0.1116,
  "pell": 0.2039,
  "men": 0.4851
 },
 "Williams": {
  "shares": {
   "white": 0.4663,
   "black": 0.0607,
   "hispanic": 0.1411,
   "asian": 0.1248,
   "aian": 0.001,
   "nhpi": 0,
   "two_or_more": 0.0747,
   "non_resident_alien": 0.0882,
   "unknown": 0.0434
  },
  "largest": "White",
  "largestPct": 47,
  "index": 71,
  "intl": 0.0882,
  "pell": 0.1761,
  "men": 0.4754
 },
 "Amherst": {
  "shares": {
   "white": 0.3642,
   "black": 0.089,
   "hispanic": 0.1381,
   "asian": 0.1648,
   "aian": 0.001,
   "nhpi": 0.0005,
   "two_or_more": 0.0863,
   "non_resident_alien": 0.1313,
   "unknown": 0.0246
  },
  "largest": "White",
  "largestPct": 36,
  "index": 78,
  "intl": 0.1313,
  "pell": 0.1984,
  "men": 0.4505
 },
 "Swarthmore": {
  "shares": {
   "white": 0.3025,
   "black": 0.0949,
   "hispanic": 0.155,
   "asian": 0.1662,
   "aian": 0.005,
   "nhpi": 0.0012,
   "two_or_more": 0.1135,
   "non_resident_alien": 0.1339,
   "unknown": 0.0279
  },
  "largest": "White",
  "largestPct": 30,
  "index": 81,
  "intl": 0.1339,
  "pell": 0.1948,
  "men": 0.4792
 },
 "Pomona": {
  "shares": {
   "white": 0.2827,
   "black": 0.0918,
   "hispanic": 0.1723,
   "asian": 0.1867,
   "aian": 0.0006,
   "nhpi": 0.0054,
   "two_or_more": 0.09,
   "non_resident_alien": 0.1369,
   "unknown": 0.0336
  },
  "largest": "White",
  "largestPct": 28,
  "index": 81,
  "intl": 0.1369,
  "pell": 0.1953,
  "men": 0.4478
 },
 "Wellesley": {
  "shares": {
   "white": 0.2983,
   "black": 0.0843,
   "hispanic": 0.1439,
   "asian": 0.257,
   "aian": 0.0009,
   "nhpi": 0.0022,
   "two_or_more": 0.077,
   "non_resident_alien": 0.1335,
   "unknown": 0.003
  },
  "largest": "White",
  "largestPct": 30,
  "index": 79,
  "intl": 0.1335,
  "pell": 0.2113,
  "men": 0.0013
 },
 "Bowdoin": {
  "shares": {
   "white": 0.527,
   "black": 0.0539,
   "hispanic": 0.1452,
   "asian": 0.1116,
   "aian": 0.0005,
   "nhpi": 0.0016,
   "two_or_more": 0.0892,
   "non_resident_alien": 0.0683,
   "unknown": 0.0027
  },
  "largest": "White",
  "largestPct": 53,
  "index": 67,
  "intl": 0.0683,
  "pell": 0.1735,
  "men": 0.4794
 },
 "Carleton": {
  "shares": {
   "white": 0.5096,
   "black": 0.059,
   "hispanic": 0.1007,
   "asian": 0.1026,
   "aian": 0.001,
   "nhpi": 0.0005,
   "two_or_more": 0.0882,
   "non_resident_alien": 0.104,
   "unknown": 0.0345
  },
  "largest": "White",
  "largestPct": 51,
  "index": 68,
  "intl": 0.104,
  "pell": 0.1653,
  "men": 0.4966
 },
 "Middlebury": {
  "shares": {
   "white": 0.542,
   "black": 0.0522,
   "hispanic": 0.1249,
   "asian": 0.0738,
   "aian": 0.0004,
   "nhpi": 0,
   "two_or_more": 0.0741,
   "non_resident_alien": 0.1231,
   "unknown": 0.0095
  },
  "largest": "White",
  "largestPct": 54,
  "index": 66,
  "intl": 0.1231,
  "pell": 0.1589,
  "men": 0.4649
 },
 "Davidson": {
  "shares": {
   "white": 0.6042,
   "black": 0.0686,
   "hispanic": 0.1114,
   "asian": 0.053,
   "aian": 0.0032,
   "nhpi": 0.0005,
   "two_or_more": 0.0418,
   "non_resident_alien": 0.1071,
   "unknown": 0.0102
  },
  "largest": "White",
  "largestPct": 60,
  "index": 59,
  "intl": 0.1071,
  "pell": 0.1759,
  "men": 0.4697
 },
 "Harvey Mudd": {
  "shares": {
   "white": 0.2443,
   "black": 0.0521,
   "hispanic": 0.2204,
   "asian": 0.202,
   "aian": 0.0033,
   "nhpi": 0.0011,
   "two_or_more": 0.1194,
   "non_resident_alien": 0.1097,
   "unknown": 0.0478
  },
  "largest": "White",
  "largestPct": 24,
  "index": 80,
  "intl": 0.1097,
  "pell": 0.1517,
  "men": 0.4929
 },
 "Claremont McKenna": {
  "shares": {
   "white": 0.3573,
   "black": 0.0411,
   "hispanic": 0.1484,
   "asian": 0.1707,
   "aian": 0,
   "nhpi": 0.0007,
   "two_or_more": 0.0872,
   "non_resident_alien": 0.1484,
   "unknown": 0.0461
  },
  "largest": "White",
  "largestPct": 36,
  "index": 77,
  "intl": 0.1484,
  "pell": 0.181,
  "men": 0.5007
 },
 "Haverford": {
  "shares": {
   "white": 0.4916,
   "black": 0.0441,
   "hispanic": 0.1147,
   "asian": 0.1294,
   "aian": 0,
   "nhpi": 0.0021,
   "two_or_more": 0.1028,
   "non_resident_alien": 0.1091,
   "unknown": 0.0063
  },
  "largest": "White",
  "largestPct": 49,
  "index": 70,
  "intl": 0.1091,
  "pell": 0.1545,
  "men": 0.4308
 },
 "Vassar": {
  "shares": {
   "white": 0.5405,
   "black": 0.0376,
   "hispanic": 0.1358,
   "asian": 0.117,
   "aian": 0.0008,
   "nhpi": 0,
   "two_or_more": 0.0814,
   "non_resident_alien": 0.0606,
   "unknown": 0.0262
  },
  "largest": "White",
  "largestPct": 54,
  "index": 65,
  "intl": 0.0606,
  "pell": 0.1924,
  "men": 0.383
 },
 "Grinnell": {
  "shares": {
   "white": 0.4841,
   "black": 0.0468,
   "hispanic": 0.0873,
   "asian": 0.0972,
   "aian": 0.0006,
   "nhpi": 0.0006,
   "two_or_more": 0.0642,
   "non_resident_alien": 0.2099,
   "unknown": 0.0093
  },
  "largest": "White",
  "largestPct": 48,
  "index": 69,
  "intl": 0.2099,
  "pell": 0.1786,
  "men": 0.4563
 },
 "Wesleyan": {
  "shares": {
   "white": 0.5357,
   "black": 0.0603,
   "hispanic": 0.1079,
   "asian": 0.0903,
   "aian": 0.0007,
   "nhpi": 0,
   "two_or_more": 0.0717,
   "non_resident_alien": 0.0991,
   "unknown": 0.0342
  },
  "largest": "White",
  "largestPct": 54,
  "index": 65,
  "intl": 0.0991,
  "pell": 0.1419,
  "men": 0.4783
 },
 "Scripps": {
  "shares": {
   "white": 0.54,
   "black": 0.0386,
   "hispanic": 0.1141,
   "asian": 0.1447,
   "aian": 0,
   "nhpi": 0,
   "two_or_more": 0.1051,
   "non_resident_alien": 0.0431,
   "unknown": 0.0144
  },
  "largest": "White",
  "largestPct": 54,
  "index": 65,
  "intl": 0.0431,
  "pell": 0.11,
  "men": 0.0009
 },
 "Pitzer": {
  "shares": {
   "white": 0.4727,
   "black": 0.0424,
   "hispanic": 0.1206,
   "asian": 0.1288,
   "aian": 0.0024,
   "nhpi": 0.0041,
   "two_or_more": 0.1002,
   "non_resident_alien": 0.0856,
   "unknown": 0.0432
  },
  "largest": "White",
  "largestPct": 47,
  "index": 70,
  "intl": 0.0856,
  "pell": 0.1055,
  "men": 0.4116
 },
 "Occidental": {
  "shares": {
   "white": 0.456,
   "black": 0.0442,
   "hispanic": 0.1763,
   "asian": 0.1609,
   "aian": 0.0021,
   "nhpi": 0.0016,
   "two_or_more": 0.098,
   "non_resident_alien": 0.0495,
   "unknown": 0.0112
  },
  "largest": "White",
  "largestPct": 46,
  "index": 71,
  "intl": 0.0495,
  "pell": 0.1656,
  "men": 0.4134
 },
 "Whitman": {
  "shares": {
   "white": 0.5604,
   "black": 0.0294,
   "hispanic": 0.13,
   "asian": 0.0549,
   "aian": 0.0039,
   "nhpi": 0.0007,
   "two_or_more": 0.0647,
   "non_resident_alien": 0.1437,
   "unknown": 0.0124
  },
  "largest": "White",
  "largestPct": 56,
  "index": 63,
  "intl": 0.1437,
  "pell": 0.1632,
  "men": 0.4278
 },
 "Reed": {
  "shares": {
   "white": 0.5826,
   "black": 0.0167,
   "hispanic": 0.1227,
   "asian": 0.0811,
   "aian": 0.003,
   "nhpi": 0,
   "two_or_more": 0.1038,
   "non_resident_alien": 0.0841,
   "unknown": 0.0061
  },
  "largest": "White",
  "largestPct": 58,
  "index": 62,
  "intl": 0.0841,
  "pell": 0.1459,
  "men": 0.4144
 },
 "Stanford": {
  "shares": {
   "white": 0.2299,
   "black": 0.0741,
   "hispanic": 0.1706,
   "asian": 0.2873,
   "aian": 0.0079,
   "nhpi": 0.0019,
   "two_or_more": 0.0958,
   "non_resident_alien": 0.1277,
   "unknown": 0.0046
  },
  "largest": "Asian",
  "largestPct": 29,
  "index": 80,
  "intl": 0.1277,
  "pell": 0.1916,
  "men": 0.4837
 },
 "Caltech": {
  "shares": {
   "white": 0.1874,
   "black": 0.0466,
   "hispanic": 0.1743,
   "asian": 0.3587,
   "aian": 0.001,
   "nhpi": 0.001,
   "two_or_more": 0.0892,
   "non_resident_alien": 0.1408,
   "unknown": 0.001
  },
  "largest": "Asian",
  "largestPct": 36,
  "index": 78,
  "intl": 0.1408,
  "pell": 0.1799,
  "men": 0.5481
 },
 "USC": {
  "shares": {
   "white": 0.2554,
   "black": 0.0708,
   "hispanic": 0.1998,
   "asian": 0.2333,
   "aian": 0.0018,
   "nhpi": 0.0022,
   "two_or_more": 0.0636,
   "non_resident_alien": 0.1328,
   "unknown": 0.0403
  },
  "largest": "White",
  "largestPct": 26,
  "index": 80,
  "intl": 0.1328,
  "pell": 0.2224,
  "men": 0.4782
 },
 "Santa Clara": {
  "shares": {
   "white": 0.3652,
   "black": 0.0337,
   "hispanic": 0.198,
   "asian": 0.2137,
   "aian": 0.0008,
   "nhpi": 0.0018,
   "two_or_more": 0.0925,
   "non_resident_alien": 0.0743,
   "unknown": 0.02
  },
  "largest": "White",
  "largestPct": 37,
  "index": 76,
  "intl": 0.0743,
  "pell": 0.1127,
  "men": 0.5055
 },
 "Loyola Marymount": {
  "shares": {
   "white": 0.382,
   "black": 0.0785,
   "hispanic": 0.2522,
   "asian": 0.1045,
   "aian": 0,
   "nhpi": 0.0011,
   "two_or_more": 0.088,
   "non_resident_alien": 0.0936,
   "unknown": 0.0001
  },
  "largest": "White",
  "largestPct": 38,
  "index": 76,
  "intl": 0.0936,
  "pell": 0.1322,
  "men": 0.4784
 },
 "University of San Diego": {
  "shares": {
   "white": 0.4304,
   "black": 0.0476,
   "hispanic": 0.2779,
   "asian": 0.07,
   "aian": 0.0019,
   "nhpi": 0.0041,
   "two_or_more": 0.0769,
   "non_resident_alien": 0.0637,
   "unknown": 0.0275
  },
  "largest": "White",
  "largestPct": 43,
  "index": 70,
  "intl": 0.0637,
  "pell": 0.2092,
  "men": 0.4355
 },
 "Pepperdine": {
  "shares": {
   "white": 0.4379,
   "black": 0.0366,
   "hispanic": 0.1942,
   "asian": 0.1464,
   "aian": 0.0031,
   "nhpi": 0.0034,
   "two_or_more": 0.0735,
   "non_resident_alien": 0.078,
   "unknown": 0.027
  },
  "largest": "White",
  "largestPct": 44,
  "index": 72,
  "intl": 0.078,
  "pell": 0.2025,
  "men": 0.4042
 },
 "Chapman": {
  "shares": {
   "white": 0.4688,
   "black": 0.0223,
   "hispanic": 0.1987,
   "asian": 0.1626,
   "aian": 0.0015,
   "nhpi": 0.0024,
   "two_or_more": 0.0892,
   "non_resident_alien": 0.0292,
   "unknown": 0.0253
  },
  "largest": "White",
  "largestPct": 47,
  "index": 69,
  "intl": 0.0292,
  "pell": 0.1939,
  "men": 0.3853
 },
 "University of Portland": {
  "shares": {
   "white": 0.3791,
   "black": 0.0301,
   "hispanic": 0.2134,
   "asian": 0.2191,
   "aian": 0.0044,
   "nhpi": 0.0142,
   "two_or_more": 0.0947,
   "non_resident_alien": 0.0321,
   "unknown": 0.0129
  },
  "largest": "White",
  "largestPct": 38,
  "index": 75,
  "intl": 0.0321,
  "pell": 0.221,
  "men": 0.3504
 },
 "Gonzaga": {
  "shares": {
   "white": 0.622,
   "black": 0.0129,
   "hispanic": 0.1449,
   "asian": 0.066,
   "aian": 0.0048,
   "nhpi": 0.0035,
   "two_or_more": 0.082,
   "non_resident_alien": 0.0496,
   "unknown": 0.0144
  },
  "largest": "White",
  "largestPct": 62,
  "index": 57,
  "intl": 0.0496,
  "pell": 0.1441,
  "men": 0.4659
 },
 "MIT": {
  "shares": {
   "white": 0.2126,
   "black": 0.077,
   "hispanic": 0.1409,
   "asian": 0.3517,
   "aian": 0.002,
   "nhpi": 0.0004,
   "two_or_more": 0.0684,
   "non_resident_alien": 0.1166,
   "unknown": 0.0304
  },
  "largest": "Asian",
  "largestPct": 35,
  "index": 77,
  "intl": 0.1166,
  "pell": 0.1932,
  "men": 0.5184
 },
 "University of Chicago": {
  "shares": {
   "white": 0.295,
   "black": 0.0687,
   "hispanic": 0.1694,
   "asian": 0.1932,
   "aian": 0.0004,
   "nhpi": 0.0003,
   "two_or_more": 0.0696,
   "non_resident_alien": 0.1764,
   "unknown": 0.0271
  },
  "largest": "White",
  "largestPct": 30,
  "index": 80,
  "intl": 0.1764,
  "pell": 0.1526,
  "men": 0.5423
 },
 "Duke": {
  "shares": {
   "white": 0.3518,
   "black": 0.0872,
   "hispanic": 0.1073,
   "asian": 0.2178,
   "aian": 0.002,
   "nhpi": 0.0008,
   "two_or_more": 0.0737,
   "non_resident_alien": 0.1054,
   "unknown": 0.054
  },
  "largest": "White",
  "largestPct": 35,
  "index": 77,
  "intl": 0.1054,
  "pell": 0.1403,
  "men": 0.4632
 },
 "Northwestern": {
  "shares": {
   "white": 0.3056,
   "black": 0.0838,
   "hispanic": 0.1575,
   "asian": 0.2122,
   "aian": 0.0015,
   "nhpi": 0.0007,
   "two_or_more": 0.0787,
   "non_resident_alien": 0.1157,
   "unknown": 0.0443
  },
  "largest": "White",
  "largestPct": 31,
  "index": 79,
  "intl": 0.1157,
  "pell": 0.1855,
  "men": 0.4568
 },
 "Johns Hopkins": {
  "shares": {
   "white": 0.195,
   "black": 0.0833,
   "hispanic": 0.1867,
   "asian": 0.2937,
   "aian": 0.0016,
   "nhpi": 0.0009,
   "two_or_more": 0.0662,
   "non_resident_alien": 0.1521,
   "unknown": 0.0206
  },
  "largest": "Asian",
  "largestPct": 29,
  "index": 80,
  "intl": 0.1521,
  "pell": 0.1949,
  "men": 0.4506
 },
 "Rice": {
  "shares": {
   "white": 0.2557,
   "black": 0.0789,
   "hispanic": 0.1669,
   "asian": 0.291,
   "aian": 0.0015,
   "nhpi": 0.0006,
   "two_or_more": 0.0555,
   "non_resident_alien": 0.1279,
   "unknown": 0.022
  },
  "largest": "Asian",
  "largestPct": 29,
  "index": 79,
  "intl": 0.1279,
  "pell": 0.1703,
  "men": 0.5042
 },
 "Vanderbilt": {
  "shares": {
   "white": 0.3905,
   "black": 0.0923,
   "hispanic": 0.1136,
   "asian": 0.1858,
   "aian": 0.0039,
   "nhpi": 0.0026,
   "two_or_more": 0.0569,
   "non_resident_alien": 0.1118,
   "unknown": 0.0426
  },
  "largest": "White",
  "largestPct": 39,
  "index": 76,
  "intl": 0.1118,
  "pell": 0.2022,
  "men": 0.4752
 },
 "Notre Dame": {
  "shares": {
   "white": 0.5939,
   "black": 0.0472,
   "hispanic": 0.1532,
   "asian": 0.0572,
   "aian": 0.0011,
   "nhpi": 0.0015,
   "two_or_more": 0.0558,
   "non_resident_alien": 0.0686,
   "unknown": 0.0215
  },
  "largest": "White",
  "largestPct": 59,
  "index": 59,
  "intl": 0.0686,
  "pell": 0.1374,
  "men": 0.5127
 },
 "Carnegie Mellon": {
  "shares": {
   "white": 0.2159,
   "black": 0.04,
   "hispanic": 0.0998,
   "asian": 0.3449,
   "aian": 0.0001,
   "nhpi": 0.0003,
   "two_or_more": 0.0535,
   "non_resident_alien": 0.1906,
   "unknown": 0.0549
  },
  "largest": "Asian",
  "largestPct": 34,
  "index": 76,
  "intl": 0.1906,
  "pell": 0.1604,
  "men": 0.5086
 },
 "Georgetown": {
  "shares": {
   "white": 0.4611,
   "black": 0.049,
   "hispanic": 0.0592,
   "asian": 0.1544,
   "aian": 0.0008,
   "nhpi": 0.0013,
   "two_or_more": 0.0639,
   "non_resident_alien": 0.1334,
   "unknown": 0.0768
  },
  "largest": "White",
  "largestPct": 46,
  "index": 69,
  "intl": 0.1334,
  "pell": 0.1012,
  "men": 0.4104
 },
 "Tufts": {
  "shares": {
   "white": 0.4063,
   "black": 0.0606,
   "hispanic": 0.1011,
   "asian": 0.1684,
   "aian": 0.0004,
   "nhpi": 0.0011,
   "two_or_more": 0.0779,
   "non_resident_alien": 0.1256,
   "unknown": 0.0585
  },
  "largest": "White",
  "largestPct": 41,
  "index": 74,
  "intl": 0.1256,
  "pell": 0.1204,
  "men": 0.4346
 },
 "Boston College": {
  "shares": {
   "white": 0.5665,
   "black": 0.0528,
   "hispanic": 0.1295,
   "asian": 0.1114,
   "aian": 0.0005,
   "nhpi": 0.0007,
   "two_or_more": 0.0508,
   "non_resident_alien": 0.0649,
   "unknown": 0.023
  },
  "largest": "White",
  "largestPct": 57,
  "index": 62,
  "intl": 0.0649,
  "pell": 0.1291,
  "men": 0.4776
 },
 "Northeastern": {
  "shares": {
   "white": 0.3986,
   "black": 0.0497,
   "hispanic": 0.1042,
   "asian": 0.2232,
   "aian": 0.0006,
   "nhpi": 0.0005,
   "two_or_more": 0.0677,
   "non_resident_alien": 0.1355,
   "unknown": 0.02
  },
  "largest": "White",
  "largestPct": 40,
  "index": 74,
  "intl": 0.1355,
  "pell": 0.1234,
  "men": 0.4343
 },
 "Boston University": {
  "shares": {
   "white": 0.3222,
   "black": 0.0592,
   "hispanic": 0.1145,
   "asian": 0.2055,
   "aian": 0.0005,
   "nhpi": 0.0009,
   "two_or_more": 0.0472,
   "non_resident_alien": 0.212,
   "unknown": 0.038
  },
  "largest": "White",
  "largestPct": 32,
  "index": 77,
  "intl": 0.212,
  "pell": 0.1915,
  "men": 0.4187
 },
 "NYU": {
  "shares": {
   "white": 0.2196,
   "black": 0.0685,
   "hispanic": 0.1437,
   "asian": 0.2224,
   "aian": 0.0017,
   "nhpi": 0.0007,
   "two_or_more": 0.0432,
   "non_resident_alien": 0.2608,
   "unknown": 0.0395
  },
  "largest": "Asian",
  "largestPct": 22,
  "index": 79,
  "intl": 0.2608,
  "pell": 0.1788,
  "men": 0.4074
 },
 "Wake Forest": {
  "shares": {
   "white": 0.6512,
   "black": 0.0644,
   "hispanic": 0.0968,
   "asian": 0.0527,
   "aian": 0.0007,
   "nhpi": 0.0015,
   "two_or_more": 0.0461,
   "non_resident_alien": 0.0578,
   "unknown": 0.0288
  },
  "largest": "White",
  "largestPct": 65,
  "index": 53,
  "intl": 0.0578,
  "pell": 0.1009,
  "men": 0.4485
 },
 "Case Western Reserve": {
  "shares": {
   "white": 0.3357,
   "black": 0.0626,
   "hispanic": 0.1164,
   "asian": 0.3048,
   "aian": 0.0008,
   "nhpi": 0.0003,
   "two_or_more": 0.0528,
   "non_resident_alien": 0.1117,
   "unknown": 0.0149
  },
  "largest": "White",
  "largestPct": 34,
  "index": 75,
  "intl": 0.1117,
  "pell": 0.1752,
  "men": 0.5206
 },
 "Tulane": {
  "shares": {
   "white": 0.6431,
   "black": 0.0726,
   "hispanic": 0.1125,
   "asian": 0.0559,
   "aian": 0.0017,
   "nhpi": 0.0009,
   "two_or_more": 0.0515,
   "non_resident_alien": 0.0485,
   "unknown": 0.0133
  },
  "largest": "White",
  "largestPct": 64,
  "index": 55,
  "intl": 0.0485,
  "pell": 0.0976,
  "men": 0.3802
 },
 "Emory": {
  "shares": {
   "white": 0.2994,
   "black": 0.1039,
   "hispanic": 0.1211,
   "asian": 0.2508,
   "aian": 0.0005,
   "nhpi": 0.0001,
   "two_or_more": 0.0419,
   "non_resident_alien": 0.1581,
   "unknown": 0.0241
  },
  "largest": "White",
  "largestPct": 30,
  "index": 78,
  "intl": 0.1581,
  "pell": 0.1821,
  "men": 0.4316
 }
};
window.CAMPUS_DIVERSITY_META={
 "source": "U.S. Department of Education College Scorecard (IPEDS Fall Enrollment)",
 "url": "https://collegescorecard.ed.gov/",
 "labels": {
  "white": "White",
  "black": "Black",
  "hispanic": "Hispanic or Latino",
  "asian": "Asian",
  "aian": "American Indian or Alaska Native",
  "nhpi": "Native Hawaiian or Pacific Islander",
  "two_or_more": "Two or more races",
  "non_resident_alien": "International",
  "unknown": "Unknown"
 },
 "notes": {
  "shares": "Share of degree-seeking undergraduates reported in each category, most recent year available.",
  "index": "Variety index, 0-100: the chance that two undergraduates picked at random report different racial or ethnic groups. Students whose group is not reported are left out of the calculation rather than counted as a group of their own.",
  "pell": "Share of undergraduates receiving a Pell grant, awarded mostly to families under roughly $60,000 of income. A campus can look varied by race and still draw from a narrow income band, so read the two together.",
  "caution": "These are counts of who enrolls. They say nothing about whether students of different backgrounds mix once they arrive, which is what a campus visit is for."
 }
};
