// generated by build_merit.py -- do not edit by hand
window.CAMPUS_MERIT={
 "UC Berkeley": {
  "pct": 2,
  "avg": 13175,
  "programs": "Regents' and Chancellor's Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Davis": {
  "pct": 3,
  "avg": 8659,
  "programs": "Regents Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Irvine": {
  "pct": 3,
  "avg": 12649,
  "programs": "Regents' Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UCLA": {
  "pct": 4,
  "avg": 8557,
  "programs": "Regents Scholarship; Alumni Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Merced": {
  "pct": 6,
  "avg": 7832,
  "programs": "Regents Scholarship; Chancellor's Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Riverside": {
  "pct": 2,
  "avg": 5791,
  "programs": "Regents Scholarship; Chancellor's Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC San Diego": {
  "pct": 3,
  "avg": 14948,
  "programs": "Regents Scholarship ($5,000/yr)",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Santa Barbara": {
  "pct": 2,
  "avg": 12372,
  "programs": "Regents Scholarship (top 2% of admits)",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "UC Santa Cruz": {
  "pct": 8,
  "avg": 8313,
  "programs": "Regents Scholarship; Campus Merit Scholarship",
  "note": "UC gives almost no merit money: the Regents Scholarship goes to roughly the top 1-2% of admits and pays a modest amount to students without need (priority enrollment and honors perks matter more than the dollars). There are no automatic GPA-based scholarships."
 },
 "CSU Bakersfield": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "CSU Channel Islands": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Chico State": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "CSU Dominguez Hills": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State East Bay": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Fresno State": {
  "pct": 6,
  "avg": 3304,
  "programs": "President's, Smittcamp Family Honors College (full)",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State Fullerton": {
  "pct": 19,
  "avg": 2590,
  "programs": "University Honors and departmental awards",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal Poly Humboldt": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State Long Beach": {
  "pct": 4,
  "avg": 1280,
  "programs": "President's Scholars (full ride, valedictorians and National Merit)",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State LA": {
  "pct": 4,
  "avg": 6655,
  "programs": "Presidential Scholars; Honors College",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State Monterey Bay": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State Northridge": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal Poly Pomona": {
  "pct": 2,
  "avg": 1255,
  "programs": "Kellogg Honors College awards",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Sacramento State": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State San Bernardino": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "San Diego State": {
  "pct": 1,
  "avg": 3811,
  "programs": "Presidential and Dean's scholarships",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "San Francisco State": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "San José State": {
  "pct": 2,
  "avg": 3146,
  "programs": "Campus scholarships",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal Poly San Luis Obispo": {
  "pct": 7,
  "avg": 3746,
  "programs": "Cal Poly Scholars and departmental awards",
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal State San Marcos": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Sonoma State": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Stanislaus State": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Cal Poly Maritime Academy": {
  "pct": null,
  "avg": null,
  "programs": null,
  "note": "CSU campuses fund small departmental, alumni, and donor scholarships (typically $500-$3,000) through one campus scholarship application each winter; there are no large automatic merit awards, but tuition is low to begin with."
 },
 "Brown": {
  "pct": 0.3,
  "avg": 21278,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Columbia": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Cornell": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Dartmouth": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Harvard": {
  "pct": 0.1,
  "avg": 6000,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Penn": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Princeton": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Yale": {
  "pct": 0.4,
  "avg": 27333,
  "programs": null,
  "note": "No merit scholarships at any Ivy: every dollar of institutional aid is need-based, so the price is set entirely by the aid formula."
 },
 "Williams": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Amherst": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Swarthmore": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Pomona": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Wellesley": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Bowdoin": {
  "pct": 2,
  "avg": 1000,
  "programs": "National Merit supplement only",
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Carleton": {
  "pct": 2,
  "avg": 15761,
  "programs": "National Merit and a few named awards",
  "note": "Almost entirely need-based; a small number of National Merit and named scholarships."
 },
 "Middlebury": {
  "pct": 0.2,
  "avg": 5000,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Davidson": {
  "pct": 3,
  "avg": 41262,
  "programs": "Belk, Baker, and Bryan Scholars (full tuition and more)",
  "note": "A few very large competitive scholarships (about 3% of no-need freshmen) rather than broad merit aid; separate application and finalist weekend."
 },
 "Harvey Mudd": {
  "pct": 17,
  "avg": 10457,
  "programs": "Harvey S. Mudd Merit Award ($10,000/yr); President's Scholars (full tuition, about 20 students)",
  "note": "Merit awards are automatic with admission for roughly one in six no-need students; the full-tuition President's Scholars program is competitive."
 },
 "Claremont McKenna": {
  "pct": 8,
  "avg": 23300,
  "programs": "McKenna Achievement Award ($20,000/yr); Interdisciplinary Science Scholarship",
  "note": "Awarded with admission to a small share of the strongest applicants; no separate application."
 },
 "Haverford": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Vassar": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Grinnell": {
  "pct": 23,
  "avg": 26154,
  "programs": "Trustee, Founders, and Presidential Scholarships (up to about $30,000/yr)",
  "note": "Merit is a deliberate strategy here: nearly a quarter of no-need freshmen get an award averaging over $26,000, considered automatically with the application."
 },
 "Wesleyan": {
  "pct": 0.1,
  "avg": 20553,
  "programs": null,
  "note": "Need-based aid only (apart from a handful of outside or National Merit awards)."
 },
 "Scripps": {
  "pct": 15,
  "avg": 24048,
  "programs": "James E. Scripps Scholarship (half tuition); New Generation Scholarship",
  "note": "Half-tuition James E. Scripps awards go to top admits; considered automatically."
 },
 "Pitzer": {
  "pct": 2,
  "avg": 7000,
  "programs": "Trustee Community Scholarship",
  "note": "Very little merit money; aid is essentially need-based."
 },
 "Occidental": {
  "pct": 29,
  "avg": 17397,
  "programs": "Presidential, Trustee, Faculty, and Dean's Scholarships (up to about $30,000/yr)",
  "note": "Nearly a third of no-need freshmen receive merit, awarded with admission based on grades and rigor; no separate application."
 },
 "Whitman": {
  "pct": 37,
  "avg": 21981,
  "programs": "Merit scholarships awarded with admission (up to about $25,000/yr)",
  "note": "The most merit-generous school in this tour: over a third of no-need freshmen get an award averaging about $22,000, decided from the application itself."
 },
 "Reed": {
  "pct": 0,
  "avg": 0,
  "programs": null,
  "note": "Reed awards aid on need only, apart from National Merit."
 }
};
window.CAMPUS_MERIT_META={
 "source": "2024-25 Common Data Set section H2A via College Transitions merit-aid table (updated November 2025)",
 "url": "https://www.collegetransitions.com/dataverse/merit-aid",
 "definition": "pct = share of first-year students with no demonstrated financial need who received a non-need-based scholarship; avg = their average award per year"
};
